README.md
docs/source/index.rst

adds the demo video to the sycamore docs page

add demo vid as additional resource

---

sycamore/tests/unit/test_writer.py
sycamore/writers/file_writer.py

This is useful for debugging element creation.

Utility function for writing out elements.

---

sycamore/transforms/map.py

Resolves https://github.com/aryn-ai/sycamore/issues/111

Inject function name while creating Ray function

---

sycamore/data/document.py
sycamore/tests/integration/transforms/test_embed.py
sycamore/transforms/embed.py
sycamore/utils/__init__.py

This change also updates the type signature for embedding to avoid an unnecessary nested list and convert from ndarray.

Add support for OpenAI embeddings.

---

sycamore/transforms/map.py
sycamore/utils/generate_ray_func.py

- This change was previously made as part of [this](https://github.com/aryn-ai/sycamore/commit/e1997214a253a89f082d83896f656310e181b362) commit but was overwritten.

Inject function name while creating Ray callables

---

docs/source/APIs/transforms/merge_elements.rst
docs/source/APIs/transforms/transforms.rst
sycamore/docset.py
sycamore/transforms/merge_elements.py

This links the merge elements transform from the main API docs page and fixes up a few issues with the doc strings.

Fix docstrings for merge elements and add to docs.

---

sycamore/scans/file_scan.py
sycamore/tests/unit/transforms/test_merge_elements.py
sycamore/transforms/explode.py
sycamore/transforms/extract_table.py
sycamore/transforms/merge_elements.py

1. Remove special handling for Titles in merge_elements
2. Support s3 paths for metadata files, currently uses the default credential provider

Merge transform fix

---

sycamore/transforms/partition.py

This is a minor thing, but I've found myself needing it twice in the past couple of weeks, so it seems worth adding. If you initialize the partitioner as `UnstructuredPdfPartitioner(retain_coordinates=True)`, then the resulting elements will have a `coordinates` property with the original Unstructured coordinates in addition to the bbox property that we compute.

Parameter to help with debugging bounding box issues.

---

sycamore/llms/llms.py
sycamore/transforms/embed.py

The openai Python SDK supports Azure, but the parameters are different. This change adds support for both.
Leaving as a draft for now, as I need to some tests against the Azure APIs.

Update OpenAI LLM and OpenAIEmbedder to also support Azure OpenAI.

---

sycamore/transforms/embed.py

Resolves https://github.com/aryn-ai/sycamore/issues/130

Provide a way to modify the text to embed

---

sycamore/reader.py
sycamore/scans/file_scan.py
sycamore/tests/unit/test_reader.py

resolves https://github.com/aryn-ai/sycamore/issues/129

Add manifest reader

---

sycamore/reader.py
sycamore/scans/file_scan.py
sycamore/tests/resources/data/json/example.json
sycamore/tests/unit/scans/test_file_scan.py
sycamore/tests/unit/test_reader.py

Resolves https://github.com/aryn-ai/sycamore/issues/113

Add basic support for JSON

---

docker_compose/README.md
docker_compose/compose.yaml
docker_compose/reset.yaml
docker_compose/sort-all.yaml

compose.yaml is the main file.
reset.yaml lets you reset persistent state back to empty.
sort-all.yaml downloads all of the sort benchmark files.

Add docker compose yaml files that run sycamore + crawler + arynai/opensearch + demoui

---

docker_compose/compose.yaml

- This lets us view the pdfs and highlighting in the containerize environment

Mount data volume to demo-ui container

---

importer/docker_local_import.py

In particular, text chunking to get larger partitions.  Note fix is from Vinayak.

Fix text chunking for html importing to improve result quality.

---

examples/html_ingest.py
examples/s3_ingest.py
examples/simple_ingest.py
sycamore/docset.py
sycamore/tests/unit/transforms/test_regex_replace.py
sycamore/transforms/__init__.py
sycamore/transforms/regex_replace.py

Includes DocSet.coalesce_whitespace() which is a simple application of regular expression replacement.

Simple transform to perform regex replacement on Elements.

---

docs/source/APIs/transforms/extract_schema.rst
docs/source/APIs/transforms/transforms.rst

Add `.rst` files to display schema and property extraction code.

Render schema extraction documentation

---

docs/source/key_concepts/transforms.rst
docs/source/key_concepts/transforms/extract_schema.md

Friendly documentation for Schema extraction

---

sycamore/llms/llms.py
sycamore/tests/unit/llms/test_llms.py

Correctly handle OpenAI model fallback.

---

examples/simple_ingest.py
sycamore/functions/simhash.py
sycamore/tests/unit/functions/test_simhash.py
sycamore/transforms/sketcher.py

These changes bring accuracy to 98% on my benchmarks.

Convert distance function from average to min.  Tune parameters.

---

.github/workflows/testing.yml
sycamore/tests/unit/transforms/test_merge_elements.py

hopefully this will fix failing integtests due to `Resource punkt not found.`

add nltk download punkt action

---

sycamore/scans/file_scan.py

In previous versions of Ray, the JSON reader did not retain the path of the input file, which led us to do JSON parsing ourself. This has been fixed in Ray 2.9.0, so we switch to using their JSON reader. This has the byproduct of also adding support for line-delimited json files (with the .jsonl extension).

Update JSON scan to use Ray JSON reader.

---

Dockerfile

For detail refer @jon's refactoring doc Sycamore Deployment - Containers https://www.notion.so/Sycamore-Deployment-Containers-91c4f7602b984e9991642f5cc8193ba9?pvs=4

Add docker image prefix as sycamore-importer.

---

importer/docker_local_import.py

For detail refer @jon's refactoring doc Sycamore Deployment - Containers https://www.notion.so/Sycamore-Deployment-Containers-91c4f7602b984e9991642f5cc8193ba9?pvs=4

Make Textract disabled by default

---

README.md
docs/source/conversation_memory/using_with_conversational_search.md

Jonfritz patch 1 docs

---

.gitignore

.gitignore file conflicts and quickstart .gitignore is a superset of sycamore one.

Prepare for merge of quickstart into sycamore.

---

docs/source/data_ingestion_and_preparation/data_preparation_concepts.md
docs/source/data_ingestion_and_preparation/generative_ai_configuration.md
docs/source/data_ingestion_and_preparation/installing_sycamore_libraries_locally.md
docs/source/data_ingestion_and_preparation/load_data.md
docs/source/data_ingestion_and_preparation/running_a_data_preparation_job.md
docs/source/data_ingestion_and_preparation/using_jupyter.md
docs/source/index.rst
docs/source/welcome_to_sycamore/architecture.md
docs/source/welcome_to_sycamore/get_started.md
docs/source/welcome_to_sycamore/hardware.md

Updates for the first part of my docs review. Please specifically review the commands under the: /running_a_data_preparation_job.md
I couldn't get these to run on my machine, but from the Docker documentation this looks correct.

Jonfritz patch 1

---

README.md
docs/source/data_ingestion_and_preparation/data_preparation_concepts.md
docs/source/data_ingestion_and_preparation/generative_ai_configuration.md
docs/source/data_ingestion_and_preparation/installing_sycamore_libraries_locally.md
docs/source/data_ingestion_and_preparation/load_data.md
docs/source/data_ingestion_and_preparation/running_a_data_preparation_job.md
docs/source/data_ingestion_and_preparation/using_jupyter.md
docs/source/index.rst
docs/source/tutorials/sycamore-jupyter-dev-example.md
docs/source/welcome_to_sycamore/get_started.md
sycamore/transforms/partition.py

* .ipnb -> .ipynb typo fix in two files
* Reformatting from running pre-commit

Fix typo in docs, and fix formatting

---

jupyter/Dockerfile
notebooks/default-prep-script.ipynb
notebooks/jupyter_dev_example.ipynb

Also add missing default-prep-script.ipynb to Dockerfile examples.

Fix examples to use https for links to UI

---

opensearch/sycamore-opensearch.sh

If $DEBUG is set to 1, debug messages will be emitted.
If $NOEXIT is set to 1, the script will sleep instead of exiting, keeping the container alive.

Add debug facility to sycamore-opensearch.sh entrypoint script.

---

opensearch/sycamore-opensearch.sh

Address two timing-related problems with SSL/security setup.

---

notebooks/default-prep-script.ipynb

No need to put the files into a non-user-owned directory.

Remove need for passwordless sudo to run the default import notebook.

---

opensearch/sycamore-opensearch.sh

This should fix opensearch version upgrading

register model if not found in setup transient

---

notebooks/jupyter_dev_example.ipynb

Switched to function for os client args, forgot to update call.

Fix bug in dev example.

---

sycamore/executor.py
sycamore/plan_nodes.py

Leaving as in-place edit for now. Probably will want to change it more later to return a non-in-place edit so that we can also do structural transforms.

Cleanup rewriting - cloning doesn't work

---

crawler/http/crawler/spiders/sycamore.py
crawler/http/tests/http_crawler_integration.sh
docs/source/data_ingestion_and_preparation/load_data.md

Fix bug in undocumented/untested prefix limiting feature.

---

poetry.lock
pyproject.toml
sycamore/tests/integration/textractor/test_textractor.py
sycamore/tests/unit/transforms/test_detr_partitioner.py
sycamore/transforms/__init__.py
sycamore/transforms/extract_table.py
sycamore/transforms/partition.py

CachedTextractTableExtractor caches textractor table extraction result into s3 for reuse.

Implement CachedTextractTableExtractor

---

apps/importer/importer/docker/importer-root-setup.sh

Add tesseract-ocr to container dependencies.

---

apps/opensearch/setup_models.py
apps/remote-processor-service/config/pipelines.yml

Perhaps you can test this in your environment.

Setup query-time NDD: pre-create RPS processors, add to pipelines

---

lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
lib/sycamore/sycamore/scans/file_scan.py
lib/sycamore/sycamore/writers/opensearch.py

There were a few deprecations and changes in the datasource API.

Upgrade to Ray 2.10.0.

---

.pre-commit-config.yaml
docs/source/querying_data/dedup.md
lib/sycamore/sycamore/data/document.py
lib/sycamore/sycamore/data/element.py
lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/functions/document.py
lib/sycamore/sycamore/scans/file_scan.py
lib/sycamore/sycamore/tests/conftest.py
lib/sycamore/sycamore/tests/unit/data/test_document.py
lib/sycamore/sycamore/tests/unit/test_docset.py
lib/sycamore/sycamore/transforms/extract_entity.py
lib/sycamore/sycamore/transforms/extract_schema.py
lib/sycamore/sycamore/transforms/extract_table.py
lib/sycamore/sycamore/transforms/partition.py
lib/sycamore/sycamore/transforms/summarize.py
notebooks/ndd_example.ipynb

Also nbstripout on the notebook.

Fix bug in updating a single property and most workarounds for the bug.

---

apps/integration/integration/automation/runtests.sh
apps/integration/integration/conftest.py
apps/integration/integration/containers/running.py
apps/integration/integration/containers/stack.py
apps/integration/integration/ingests/crawler.py
apps/integration/integration/ingests/index.py
apps/integration/integration/ingests/jupyter.py
apps/integration/integration/queries/queries.py

- Jupyter testing
- Create compose stack as a fixture
- provide a tag to run tests against

Better container integration testing automation

---

lib/sycamore/sycamore/data/__init__.py
lib/sycamore/sycamore/data/bbox.py
lib/sycamore/sycamore/data/table.py
lib/sycamore/sycamore/tests/unit/data/test_bbox.py
lib/sycamore/sycamore/tests/unit/data/test_table.py

This PR introduces a logical Table class that can be used to represent the data in a document table in a format independent way. It is based on representations used by TableTransformers and Textract, among others. This commit just adds the basic data structure and some format conversions and tests. Actual table understanding models will be added in a follow-up PR.
This also includes some enhancements to the BoundingBox class so that it can be used with a variety of table models.

Update data model for table structure recognition.

---

apps/demo-ui/Dockerfile.build
apps/demo-ui/Dockerfile.buildx
apps/demo-ui/openai-proxy/py_proxy/proxy.py
apps/demo-ui/openai-proxy/py_proxy/token_proxy.py
apps/demo-ui/run-ui.sh
apps/demo-ui/sudoers

Implemented as per: https://www.notion.so/Protecting-the-UI-with-a-Token-f8b562ea8a9e434db3895971bd08037a?pvs=4
Also fixes issue #308.

Put token-protected HTTPS proxy in front of UI proxy.

---

apps/jupyter/Dockerfile.buildx
apps/jupyter/jupyter-docker-root-setup.sh
lib/sycamore/sycamore/tests/unit/data/test_table.py
notebooks/default-prep-script.ipynb
notebooks/jupyter_dev_example.ipynb

* Add aws cli to jupyter container
* Remove URL from notebooks since localhost won't work in cloud service

Jupyter container improvements

---

docs/source/data_ingestion_and_preparation/transforms/partition.md

Added documentation for our PDF and HTML partitioners.

Jonfritz patch 1 partition update

---

apps/demo-ui/ui/src/App.tsx
apps/demo-ui/ui/src/Chatbox.tsx
apps/demo-ui/ui/src/ConversationList.tsx

A user can now initiate a conversation by asking a question, without having to create a conversation ID beforehand.

FIX: Error on initiate conversation without a conversation id 

---

apps/remote-processor-service/README.md
lib/remote-processors/README.md
lib/remote-processors/remote_processors/server/remote_processor_service.py
lib/remote-processors/remote_processors/test/unit/service/test_remote_processor_service.py

Done via:
```
find . -type f -print0 | grep -zFv /. | grep -zEv '__pycache__|node_modules' | xargs -r0 sed -i -E -e 's/ProcessResponseRequest/ProcessResponseCall/g' -e 's/ProcessResponseResponse/ProcessResponseReply/g'
```

Rename ...Request -> ...Call and ...Response -> ...Reply

---

apps/demo-ui/ui/src/App.tsx
apps/demo-ui/ui/src/Chatbox.tsx
apps/demo-ui/ui/src/Controlpanel.tsx
apps/demo-ui/ui/src/ConversationList.tsx

This PR makes the Demo UI adapt to different screen sizes across various devices.

Responsive Demo UI

---

lib/sycamore/sycamore/data/__init__.py
lib/sycamore/sycamore/data/document.py
lib/sycamore/sycamore/tests/unit/data/test_document.py
lib/sycamore/sycamore/tests/unit/transforms/test_base.py
lib/sycamore/sycamore/transforms/base.py

* Add new MetadataDocument subclass that stores metadata and raises errors if tried to be used as a document.
* Add BaseMap class that processes documents, passes through metadata, and automatically generate lineage links.

lineage 1/n: add support for metadata.

---

lib/sycamore/sycamore/data/document.py
lib/sycamore/sycamore/tests/integration/transforms/test_embed.py
lib/sycamore/sycamore/tests/unit/data/test_document.py

* Document class started using the elements parameter, test_embed was setting them in an incompatible way
* Add additional checking so that the error message is clearer.

Fix integration tests.

---

lib/sycamore/sycamore/llms/openai.py
lib/sycamore/sycamore/transforms/summarize_images.py

Also switched the SummarizeImages transform to use it by default.

Add GPT-4o support.

---

apps/demo-ui/ui/src/App.tsx
apps/demo-ui/ui/src/Chatbox.tsx
apps/demo-ui/ui/src/Controlpanel.tsx
apps/demo-ui/ui/src/ConversationList.tsx
apps/demo-ui/ui/src/Doclist.tsx
apps/demo-ui/ui/src/PdfViewer.tsx

- Changes to the main container of the demo
- Options footer moved to the settings modal

Updates to Demo UI

---

lib/sycamore/sycamore/tests/unit/transforms/test_base.py
lib/sycamore/sycamore/tests/unit/transforms/test_mapping.py
lib/sycamore/sycamore/transforms/base.py
lib/sycamore/sycamore/transforms/bbox_merge.py
lib/sycamore/sycamore/transforms/explode.py
lib/sycamore/sycamore/transforms/extract_entity.py
lib/sycamore/sycamore/transforms/extract_schema.py
lib/sycamore/sycamore/transforms/map.py
lib/sycamore/sycamore/transforms/mark_misc.py
lib/sycamore/sycamore/transforms/partition.py
lib/sycamore/sycamore/transforms/regex_replace.py
lib/sycamore/sycamore/transforms/sketcher.py
lib/sycamore/sycamore/transforms/split_elements.py
lib/sycamore/sycamore/transforms/spread_properties.py
lib/sycamore/sycamore/transforms/summarize.py
lib/sycamore/sycamore/utils/__init__.py
lib/sycamore/sycamore/utils/generate_ray_func.py

* Remove some unused generate_* functions
* Adjust transforms to import the generate function from the original source rather than map since map no longer uses them. Ideally we'll remove all ray specific bits from the transforms when converting them over.

Convert map.py transforms over to base map.

---

lib/sycamore/sycamore/tests/unit/data/test_document.py
lib/sycamore/sycamore/tests/unit/transforms/test_bbox_merge.py
lib/sycamore/sycamore/transforms/bbox_merge.py
lib/sycamore/sycamore/transforms/map.py
lib/sycamore/sycamore/transforms/mark_misc.py

* Started with bbox_merge, but the test file also covers mark_misc so did both.
* Added helper function to map to run the function since that was used in the tests.
* Fixed bug in map wrapper and the same bug in the flat_map wrapper

Convert bbox_merge and mark_misc to new Map style

---

apps/demo-ui/openai-proxy/py_proxy/proxy.py
apps/demo-ui/ui/src/App.tsx
apps/demo-ui/ui/src/Chatbox.tsx
apps/demo-ui/ui/src/Controlpanel.tsx

Let's you configure features with runtime variables when running in a containers.

Use proxy to provide default settings to the UI

---

CONTRIBUTING.md

* Sundry lint fixes also applied

Update CONTRIBUTING.md to note that integration tests are currently broken.

---

lib/sycamore/sycamore/transforms/merge_elements.py

This allows more flexible scheduling of the work.

Convert Merge from Ray Actor to Ray Task.

---

lib/sycamore/sycamore/rules/optimize_resource_args.py
lib/sycamore/sycamore/tests/unit/test_docset.py
lib/sycamore/sycamore/tests/unit/test_rewriter.py
lib/sycamore/sycamore/tests/unit/transforms/test_base.py
lib/sycamore/sycamore/transforms/base.py
lib/sycamore/sycamore/transforms/basics.py
lib/sycamore/sycamore/transforms/embed.py

* Add support for new "object called as class or function" mode.
* Fix bug where specifying num_gpus = 0 in resource args causes problems because ray thinks that means it needs a GPU. Turns out existing code wasn't passing in resource_args.

Switch Filter and Enbed over to BaseMapTransform

---

lib/sycamore/sycamore/tests/unit/test_docset.py
lib/sycamore/sycamore/tests/unit/transforms/test_explode.py
lib/sycamore/sycamore/tests/unit/transforms/test_mapping.py
lib/sycamore/sycamore/transforms/augment_text.py
lib/sycamore/sycamore/transforms/explode.py
lib/sycamore/sycamore/transforms/extract_entity.py
lib/sycamore/sycamore/transforms/query.py
lib/sycamore/sycamore/transforms/summarize_images.py
lib/sycamore/sycamore/transforms/table_structure/extract.py
lib/sycamore/sycamore/utils/__init__.py
lib/sycamore/sycamore/utils/generate_ray_func.py

* Remove now unused functions in generate_ray_func.py

Convert classes over to new *Map classes 3/n

---

lib/sycamore/sycamore/tests/unit/transforms/test_base.py
lib/sycamore/sycamore/transforms/base.py
lib/sycamore/sycamore/transforms/partition.py

* Add new Composite class that models multiple composite operations in a single node
* Use it to rewrite partition which is a sometime composite operation.

Conversion to base map 5/n: Partition

---

examples/ndd.py
examples/ndd_debug.py
lib/sycamore/sycamore/tests/unit/transforms/test_sketcher.py
lib/sycamore/sycamore/tests/unit/transforms/test_spread_properties.py
lib/sycamore/sycamore/transforms/sketcher.py
lib/sycamore/sycamore/transforms/spread_properties.py

Switch spread props & ndd to BaseMap -- *Map 7/n

---

docs/source/data_ingestion_and_preparation/transforms/partition.md

fixed typo in line ctx = scyamore.init()

fixed typo

---

apps/demo-ui/openai-proxy/py_proxy/proxy.py
apps/demo-ui/openai-proxy/py_proxy/token_proxy.py
apps/demo-ui/ui/src/App.tsx
apps/demo-ui/ui/src/Chatbox.tsx
apps/demo-ui/ui/src/Controlpanel.tsx
apps/demo-ui/ui/src/ConversationList.tsx
apps/demo-ui/ui/src/OpenSearch.tsx
apps/demo-ui/ui/src/PdfViewer.css
apps/demo-ui/ui/src/PdfViewer.tsx
apps/demo-ui/ui/src/Types.tsx

Updates to the DEMO UI
- New PDF viewer
- Proxy Cache Functionality
- Error Dialog box

Soham demo UI updates

---

lib/sycamore/sycamore/transforms/detr_partitioner.py
lib/sycamore/sycamore/transforms/embed.py
lib/sycamore/sycamore/transforms/partition.py
lib/sycamore/sycamore/transforms/table_structure/extract.py
lib/sycamore/sycamore/utils/__init__.py

Some of our tests are unable to run on laptops because they try to use the gpu, but specify multiple stages that both need the GPU so hang indefinitely.

Allow disabling CUDA via env var

---

lib/sycamore/sycamore/transforms/detr_partitioner.py

Tested on my laptop both cases (older and younger than cutoff).

Lazily clean up temp files from DETR partitioner.

---

apps/demo-ui/ui/src/Types.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/AddAggregationModal.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/AddFilterModal.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/Doclist.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/OpenSearchQueryEditor.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/SearchControlPanel.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/SystemChatbox.tsx
apps/demo-ui/ui/src/pages/HomePage/components/Chatbox/index.tsx
apps/demo-ui/ui/src/utils/ChatboxUtils.tsx
apps/demo-ui/ui/src/utils/Llm.tsx
apps/demo-ui/ui/src/utils/queryPlannerPrompt.ts

1. Updates from BB demo UI
2. New Feature for Manual Filters and Aggregations on Input Query
- Can be turned on using the "auto-filter" flag

Demo UI feature for Manual Filters and Aggregations on input query

---

lib/sycamore/sycamore/functions/__init__.py

OpenAITokenizer class added to sycamore.functions package

Adding OpenAITokenizer to sycamore.functions

---

lib/sycamore/sycamore/transforms/detr_partitioner.py

Send images to detr model as a batch instead of in a loop

Batch detr inference

---

lib/sycamore/sycamore/data/bbox.py
lib/sycamore/sycamore/writer.py
lib/sycamore/sycamore/writers/pinecone_writer.py

This one is largely mechanical, to the degree that one of these can be mechanical.
n.b. I added a `to_dict()` method to bbox that returns the coords named. useful for flattening etc

convert pinecone writer to base writer 3/3

---

lib/sycamore/sycamore/transforms/detr_partitioner.py
lib/sycamore/sycamore/transforms/partition.py

Remove old model server client

Remove old model server endpoint option

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/tests/unit/test_docset.py

This is just a convenience method that behaves like map_elements.

Add filter_elements method on DocSet.

---

lib/sycamore/sycamore/data/bbox.py
lib/sycamore/sycamore/data/element.py
lib/sycamore/sycamore/data/table.py
lib/sycamore/sycamore/tests/unit/data/test_table.py

This is necessary to deserialize a Document containing a table from the ArynPartitioner.

Support table deserialization from a dictionary.

---

lib/sycamore/sycamore/llms/llms.py
lib/sycamore/sycamore/llms/openai.py
lib/sycamore/sycamore/tests/integration/llms/test_openai.py
lib/sycamore/sycamore/tests/unit/transforms/compare_detr_impls.py
lib/sycamore/sycamore/tests/unit/utils/test_cache.py
lib/sycamore/sycamore/tests/unit/utils/test_cache_manager.py
lib/sycamore/sycamore/transforms/detr_partitioner.py
lib/sycamore/sycamore/utils/cache.py
lib/sycamore/sycamore/utils/cache_manager.py
lib/sycamore/sycamore/utils/pdf.py

1. Add a basic S3 cache implementation
2. Allow caching for exact LLM calls

Add S3 cache implementation, add cache option to Llm

---

lib/sycamore/sycamore/connectors/weaviate/weaviate_writer.py
lib/sycamore/sycamore/connectors/writers/common.py
lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
lib/sycamore/sycamore/tests/unit/connectors/weaviate/test_weaviate.py
lib/sycamore/sycamore/tests/unit/connectors/writers/test_common.py

adds a whole bunch of unit tests for the opensearch writer, weaviate writer, and some common functions
also fixed bugs that those tests exposed

Add some writer unit tests

---

lib/sycamore/sycamore/tests/integration/transforms/test_partition.py
lib/sycamore/sycamore/tests/unit/transforms/test_aryn_partitioner.py
lib/sycamore/sycamore/transforms/aryn_partitioner.py
lib/sycamore/sycamore/transforms/partition.py
lib/sycamore/sycamore/utils/aryn_config.py

Check `$ARYN_API_KEY` and read `.aryn/config.yaml` in that order to find the Aryn token (Aryn API Key).

Extract Aryn token from config for ArynPartitioner

---

lib/sycamore/sycamore/transforms/detr_partitioner.py
lib/sycamore/sycamore/utils/pdf.py

This reverts commit 8f994aec7f43d5047322932813dea3b1e3c38460.

Revert "Add PDF to Image cache (#501)"

---

lib/sycamore/sycamore/transforms/detr_partitioner.py

This improves performance by a signficant amount (order 2x).

Move initialization of easyocr Reader to Actor level.

---

notebooks/jupyter_dev_example.ipynb

The import of `sycamore.scans.file_scan` is incorrect.

Fix example Jupyter notebook.

---

lib/sycamore/sycamore/tests/integration/connectors/pinecone/test_pinecone_scan.py

Fixes the `test_pinecone_scan` integration test that was not working due to eventual consistency issues

Fix Pinecone Test

---

lib/sycamore/sycamore/transforms/partition.py

I'm like 96% sure that this is incorrect in some way, so please read

Fix partitioner docstring

---

docs/source/data_ingestion_and_preparation/connectors/elasticsearch.md
docs/source/data_ingestion_and_preparation/connectors/weaviate.md
lib/sycamore/sycamore/connectors/common.py
lib/sycamore/sycamore/connectors/elasticsearch/elasticsearch_writer.py
lib/sycamore/sycamore/tests/unit/test_writer.py
lib/sycamore/sycamore/writer.py
notebooks/elasticsearch-writer.ipynb

This PR adds a demo notebook for Elasticsearch and respective customer facing documentation

Add Elasticsearch Demo Notebook and Docs

---

notebooks/duckdb-writer.ipynb
notebooks/elasticsearch-writer.ipynb
notebooks/pinecone-writer.ipynb

Moves the notebooks to the Aryn Partitioner

Move Writer Notebooks to ArynPartitioner

---

lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py

Reverts Opensearch document parsing behavior

Revert Opensearch Reader Behavior

---

lib/sycamore/sycamore/utils/http.py

Added a new `cache` argument to `post()`.  The code will look in the cache using the path (without @) as the key before trying to read from the filesystem.  Example usage:
```
with open(path, "rb") as fp
buf = fp.read()
hdr = {"Authorization": f"Bearer {tok}"}
form = {
"options": '{"use_foo": true}',
"input": f"@{path}",
}
cache = {path: buf}
c = OneShotKaClient(url)
res = c.post(headers=hdr, form=form, cache=cache)
```

Can avoid the filesystem when posting files.

---

docs/source/data_ingestion_and_preparation/connectors/duckdb.md
docs/source/data_ingestion_and_preparation/connectors/elasticsearch.md
docs/source/data_ingestion_and_preparation/connectors/pinecone.md
docs/source/data_ingestion_and_preparation/connectors/weaviate.md
lib/sycamore/sycamore/connectors/duckdb/duckdb_reader.py
lib/sycamore/sycamore/connectors/file/file_scan.py
lib/sycamore/sycamore/reader.py
lib/sycamore/sycamore/tests/unit/test_reader.py
lib/sycamore/sycamore/writer.py

Adds extensive reader docs and fixes small errors found in the process

Add Reader Docs

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/tests/unit/transforms/test_llm_query.py
lib/sycamore/sycamore/transforms/__init__.py
lib/sycamore/sycamore/transforms/llm_query.py

Adds querying an OpenAI LLM using a user defined prompt as a transform

Add LLM Query as a Transform

---

.gitignore
docs/source/data_ingestion_and_preparation/connectors/elasticsearch.md
docs/source/data_ingestion_and_preparation/connectors/opensearch.md
docs/source/data_ingestion_and_preparation/connectors/weaviate.md

Fixes an indent issue in the docs and removes an erroneous addition to `gitignore`

Fix Indent in Docs

---

apps/query-ui/queryui/queryui.py
lib/sycamore/sycamore/query/README.md
lib/sycamore/sycamore/query/client.py
lib/sycamore/sycamore/query/execution/metrics.py
lib/sycamore/sycamore/query/execution/sycamore_executor.py
lib/sycamore/sycamore/query/execution/sycamore_operator.py
notebooks/query-demo.ipynb

This PR also adds `notebooks/query-demo.ipynb` to demonstrate using Sycamore Query in a Jupyter notebook.

Rename LunaClient to SycamoreQueryClient.

---

lib/sycamore/sycamore/tests/manual/pdf2image_memusage.py
lib/sycamore/sycamore/utils/pdf.py

Will remove the old code once everything is switched over.

Add code to convert pdf to images via files.

---

lib/sycamore/sycamore/query/execution/operations.py
lib/sycamore/sycamore/query/execution/sycamore_executor.py
lib/sycamore/sycamore/query/execution/sycamore_operator.py
lib/sycamore/sycamore/query/operators/count.py
lib/sycamore/sycamore/query/operators/filter.py
lib/sycamore/sycamore/query/operators/join.py
lib/sycamore/sycamore/query/operators/limit.py
lib/sycamore/sycamore/query/operators/llmextract.py
lib/sycamore/sycamore/query/operators/llmfilter.py
lib/sycamore/sycamore/query/operators/llmgenerate.py
lib/sycamore/sycamore/query/operators/loaddata.py
lib/sycamore/sycamore/query/operators/logical_operator.py
lib/sycamore/sycamore/query/operators/math.py
lib/sycamore/sycamore/query/operators/sort.py
lib/sycamore/sycamore/query/operators/topk.py
lib/sycamore/sycamore/query/planner.py
lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_operator.py
lib/sycamore/sycamore/tests/unit/query/test_operations.py

- Update prompting for operators and planner
- Add infrastructure + tests for join operator
- Make small fixes that were causing queries to fail

Changes to operators/prompting to support more queries

---

apps/query-ui/queryui/queryui.py

For some reason I'm not getting cache hits, which is odd, but I don't think that has to do with the streamlit app.

Add caching and fix query logic.

---

lib/sycamore/sycamore/transforms/partition.py

Moves transcript processing code into Sycamore

Add Transcript Processing

---

.github/workflows/testing.yml
README.md

apt install poppler and tesseract is failling on #560 so Ima debug the workflow here

debug the workflow

---

lib/sycamore/sycamore/data/document.py

Document why we didn't apply the change suggested in https://github.com/aryn-ai/sycamore/issues/597

Add comment to MetadataDocument superclass call

---

lib/sycamore/sycamore/tests/integration/query/conftest.py

Reduces number of elements from ~250 to 3, this results in a big reduction in LLM calls since that's what these tests currently do. The 1000 tokens number is made up, it probably results in a loss of answer quality but that's not what these tests are for.

Merge elements in ntsb test ingest

---

lib/sycamore/sycamore/data/document.py
lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/query/execution/operations.py
lib/sycamore/sycamore/query/execution/sycamore_operator.py
lib/sycamore/sycamore/query/planner.py
lib/sycamore/sycamore/query/schema.py
lib/sycamore/sycamore/tests/integration/query/execution/test_sycamore_query.py
lib/sycamore/sycamore/tests/unit/functions/test_field_to_value.py
lib/sycamore/sycamore/tests/unit/query/test_operations.py
lib/sycamore/sycamore/transforms/extract_entity.py
lib/sycamore/sycamore/transforms/sort.py

- Make `field_to_value` return None as a default, if the field does not exist
- Related updates in places this function is used

Small update to `field_to_value`

---

docs/source/aryn_cloud/aryn_partitioning_service.md

Added some info to the Aryn Partitioning Service section.

Jonfritz patch docsupdate

---

.github/workflows/testing.yml
lib/sycamore/sycamore/context.py
lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/lineage.py
lib/sycamore/sycamore/tests/unit/test_lineage.py

Several ways to configure for high customizability.

Add support to materialize to write documents out to files.

---

apps/query-ui/queryui/queryui.py
lib/sycamore/sycamore/query/client.py
lib/sycamore/sycamore/query/planner.py
lib/sycamore/sycamore/query/schema.py
lib/sycamore/sycamore/tests/integration/query/test_planner.py
lib/sycamore/sycamore/tests/unit/query/test_schema.py

Should make retrieval of the schema more robust when there are mapping fields not present in the examples.

Refactor OpenSearchSchema to be more robust.

---

apps/query-ui/queryui/queryui.py
lib/sycamore/sycamore/query/execution/sycamore_executor.py
lib/sycamore/sycamore/query/execution/sycamore_operator.py

- Button to execute generated code and result is printed out (this will also allow us to test/tweak codegen)
- Traces after each node displayed as scrollable/expandable/searchable pandas dataframe
- Button to download traces for a query as a zip file
- Added some error handling
If you want to switch to the branch + try it out and give feedback, that would be great! I can also demo it on Monday.

Fix code execution and trace display in Query UI

---

lib/sycamore/sycamore/plan_nodes.py
lib/sycamore/sycamore/tests/unit/test_node.py

Handles both before and after transforms and properly handles adjustments to the structure.

Add generic traverse

---

lib/sycamore/sycamore/query/execution/sycamore_operator.py
notebooks/OpenAI logprob.ipynb

Fixed some typos, formatting, and structure. Ran the queries successfully through the benchmark

Fix codegen syntax/formatting

---

lib/sycamore/sycamore/query/execution/sycamore_executor.py
lib/sycamore/sycamore/tests/integration/query/execution/test_sycamore_query.py

Execution condition was missing a check

Bugfix for query dry-run mode

---

.github/workflows/testing.yml
lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/tests/integration/connectors/neo4j/test_docset_to_neo4j.py
lib/sycamore/sycamore/tests/unit/transforms/test_graph_extractor.py
lib/sycamore/sycamore/transforms/extract_graph.py

This PR implements some of the boilerplate code for the graph extractor that I was running manually. Cleans up the integration test & now people should be able to use a graph extractor pipeline end to end.

implemented boilerplate transforms of documents.

---

docs/source/sycamore/transforms.rst
docs/source/sycamore/transforms/filter.md

I also included filter_element on the same page. I could split it out separately, but not sure how useful that is.

Add filter docs.

---

docs/source/sycamore/tutorials.rst
docs/source/sycamore/tutorials/etl_for_opensearch.md

Update tutorial and remove old tutorial from ToC

Update tutorial and remove old tutorial from ToC

---

lib/sycamore/sycamore/tests/unit/scans/test_file_scan.py

We added extra json files. Only example.json has the expected content.

Fix flaky test.

---

.github/workflows/testing.yml
lib/sycamore/sycamore/connectors/file/__init__.py
lib/sycamore/sycamore/connectors/file/file_scan.py
lib/sycamore/sycamore/connectors/file/file_writer.py
lib/sycamore/sycamore/connectors/file/file_writer_ray.py
lib/sycamore/sycamore/connectors/file/materialized_scan.py
lib/sycamore/sycamore/tests/manual/test_fast_sycamore_import.py
lib/sycamore/sycamore/tests/unit/transforms/test_base.py
lib/sycamore/sycamore/transforms/base.py
lib/sycamore/sycamore/transforms/basics.py
lib/sycamore/sycamore/transforms/dataset_scan.py
lib/sycamore/sycamore/transforms/embed.py
lib/sycamore/sycamore/transforms/extract_schema.py
lib/sycamore/sycamore/transforms/groupby_count.py
lib/sycamore/sycamore/transforms/partition.py
lib/sycamore/sycamore/transforms/random_sample.py
lib/sycamore/sycamore/transforms/sketcher.py
lib/sycamore/sycamore/transforms/sort.py
lib/sycamore/sycamore/writer.py

import ray is about 0.2s, import sycamore about 3s, so ~10% speedup.
First step of many, but this one was pretty mechanical.

import sycamore does not import ray

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/materialize.py
lib/sycamore/sycamore/tests/unit/test_materialize.py

Files were made before we agreed on name.

Rename lineage files to materialize.

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/executor.py
lib/sycamore/sycamore/materialize.py
lib/sycamore/sycamore/materialize_config.py
lib/sycamore/sycamore/plan_nodes.py
lib/sycamore/sycamore/query/execution/aggregation.py
lib/sycamore/sycamore/reader.py
lib/sycamore/sycamore/tests/integration/test_materialize.py
lib/sycamore/sycamore/tests/unit/test_docset.py
lib/sycamore/sycamore/tests/unit/test_executor.py
lib/sycamore/sycamore/tests/unit/test_materialize.py
lib/sycamore/sycamore/transforms/extract_graph.py

Rewrite execution so that we have a finalize() operation that runs if execution runs to completion. This makes reading from materialized output usable because we can now be sure that we have a final execution of the pipeline.

Add IF_PRESENT reading mode to materialize

---

lib/sycamore/pyproject.toml

I'll ping someone when we're ready

bump sycamore version from 0.1.18 to 0.1.19

---

lib/sycamore/sycamore/data/table.py

Fixes TypeError: sequence item 1: expected str instance, NoneType found

Fix Nonetype Error

---

docs/source/sycamore/transforms/materialize.md
lib/sycamore/sycamore/docset.py

Copy over documentation from docset to transforms/materialize.md Copy some examples from the upcoming blog post.

More materialize documentation

---

lib/sycamore/sycamore/connectors/file/file_scan.py
lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/transforms/base.py
lib/sycamore/sycamore/utils/lineage_utils.py

Adds the ability to be able to run most notebooks using `ExecMode.LOCAL`

Add Local Mode Support for Composite Transform and Binary Read

---

lib/sycamore/sycamore/data/element.py
lib/sycamore/sycamore/tests/unit/data/test_document.py

Triggered by https://github.com/aryn-ai/sycamore/blob/eb27e29f4938c383288066fada8f8ffe1952c277/lib/sycamore/sycamore/transforms/table_structure/extract.py#L168

Handle None cases for element.table = <>

---

lib/sycamore/sycamore/executor.py
lib/sycamore/sycamore/materialize.py
lib/sycamore/sycamore/tests/unit/inmempyarrowfs.py
lib/sycamore/sycamore/tests/unit/test_materialize.py

Existing code was relying on python pathlib to do most operations rather than running them through the pyarrow filesystem.  Fix that, and add a test with a fake pyarrow filesystem to make sure we run with a path that does not exist in the local filesystem.

Fix materialize + S3 not working.

---

lib/sycamore/sycamore/tests/unit/test_context.py
lib/sycamore/sycamore/tests/unit/text_context.py

Naming is hard. Also the rules on context creation have changed, check the current rules.

Fix context test

---

notebooks/sycamore-tutorial-intermediate-etl.ipynb

Adding new ETL tutorial

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/materialize.py
lib/sycamore/sycamore/tests/unit/test_materialize.py

Since we want to support clearing via the docset abstraction, we need a way to specify what to clear so people can a subset of the pipeline.

add clear_materialize(path=<something>)

---

docs/source/aryn_cloud/aryn_partitioning_service.rst
docs/source/aryn_cloud/using_the_console.md

Jonfritz patch 3 consoledocs

---

apps/query-demo/querydemo/Query_Demo.py

This fixes a bug whereby multiple widgets with the same key sometimes pop up.

Fix issue with duplicate widget keys.

---

apps/query-ui/queryui/Sycamore_Query.py
apps/query-ui/queryui/custom_client.py
apps/query-ui/queryui/util.py
lib/sycamore/sycamore/context.py
lib/sycamore/sycamore/query/client.py
lib/sycamore/sycamore/query/planner.py
lib/sycamore/sycamore/query/schema.py
lib/sycamore/sycamore/tests/unit/query/test_schema.py

1. Some planner prompt changes to get more "reliable" JSON results :/
2. Index schema related bug fixes. Also look at more sample records but cap the number of actual example values used
3. Bugs

Bug fixes in query path

---

apps/query-demo/querydemo/Query_Demo.py
apps/query-demo/querydemo/main.py
apps/query-demo/querydemo/util.py

This incorporates a version of Eric's workaround for Ray issues in the `eric-containers` branch into the new NTSB demo, and a few UI tweaks to make it more usable.

A few Luna demo fixes.

---

notebooks/opensearch_docs_etl.ipynb

Add new OpenSearch writer notebook for use with the OpenSearch documentation as a getting started example.

Add new OpenSearch writer notebook

---

lib/sycamore/sycamore/tests/unit/transforms/test_table_transfomers.py
lib/sycamore/sycamore/transforms/table_structure/table_transformers.py

Adds a check to ensure we only create valid BoundingBoxes

Fix TableTransformer Bug

---

.gitignore
Makefile
docs/Makefile
lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/tests/integration/transforms/test_map.py
lib/sycamore/sycamore/transforms/map.py

* Add integration test confirming it works.
* Add documentation explaining how.
* Add support for viewing the readthedocs documentation before committing.

Verify .map can run parallel classes

---

lib/sycamore/sycamore/data/bbox.py

Added a TODO to ensure that we get back to this.

Change Bounding Box Validity Assertion

---

apps/query-demo/querydemo/Query_Demo.py

Fixes issue where tool response is lost on rerun. Drop verbose LLM prompt. Fix a merge issue.

Couple of Luna demo bugfixes.

---

apps/query-ui/queryui/Sycamore_Query.py
apps/query-ui/queryui/util.py

Quick change to print docset results to be readable

query-ui: cosmetic changes

---

apps/query-demo/querydemo/loaddata.py

This PR adds a few additional fields to OpenSearch from the NTSB documents, to help optimize common queries.

Ingest more fields into OpenSearch schema for NTSB demo.

---

lib/sycamore/sycamore/tests/unit/transforms/test_merge_elements.py
lib/sycamore/sycamore/transforms/merge_elements.py

The tokenizer was receiving a Dict instead of text, causing the code to break.

fix to pass string to tokenizer

---

pyproject.toml

Need poetry 1.8 everywhere to avoid the warning.

Remove package-mode

---

lib/aryn-sdk/aryn_sdk/partition/partition.py
lib/aryn-sdk/pyproject.toml

- if you give me a path, read in the file at the path
- fix that thing where you'd always get a warning on passing in an API key

handle file paths in the sdk

---

lib/aryn-sdk/poetry.lock
lib/aryn-sdk/pyproject.toml

This appears to be a required dependency.

Add packaging library to aryn-sdk pyproject.toml.

---

lib/sycamore/sycamore/tests/unit/utils/test_markdown.py
lib/sycamore/sycamore/utils/markdown.py

I'm not touching the "styling" characters (italic, bold, etc.) because we may get then from OCR.

Do some escaping of special Markdown characters.

---

lib/aryn-sdk/aryn_sdk/partition/partition.py

since now we allow these types

fix type annotation for file

---

.gitignore

This includes a few more dist/ directories, the ttviz binary, and .python-version files that are created by pyenv.

Add a few more files to .gitignore.

---

lib/sycamore/sycamore/transforms/table_structure/table_transformers.py

fix issue when packages and containers do not align at all -> max([])

---

examples/query/ntsb_loader_materialized.py
lib/sycamore/sycamore/materialize.py
lib/sycamore/sycamore/tests/unit/utils/test_sycamore_logger.py
lib/sycamore/sycamore/utils/sycamore_logger.py

* In materialize, try reading using the credentials, but if it doesn't work, fall back to reading anonymously if that seems to be working.
* Add rate limited logging to reading via materialize in local mode.
* Check for no root before checking if a source since that makes more sense.
* switch ntsb_loader_materialized.py over to read in local mode, it was working (with the anonymous fix), but was very slow hence the logging.

Fix anonymous reading in materialize and add rate limited logging.

---

lib/sycamore/sycamore/data/bbox.py

saves like less than a millisecond but that can add up https://github.com/aryn-ai/managed-service/pull/572
mostly this is for parity

microperformance improvement

---

apps/query-server/queryserver/util.py
apps/query-ui/queryui/util.py
lib/sycamore/sycamore/query/client.py

Added the ability to read the schema from a file instead of OS.

added ability to read schema from file

---

lib/sycamore/sycamore/tests/integration/transforms/test_random_sample.py
lib/sycamore/sycamore/tests/unit/transforms/test_random_sample.py
lib/sycamore/sycamore/transforms/random_sample.py

This transform isn't widely used, but still worth supporting in local model to bring it to parity.

Support random sample in local mode.

---

lib/sycamore/sycamore/query/client.py

Was not allowing an index to be specified without schema.

Fix small bug in client.

---

apps/query-eval/queryeval/driver.py
apps/query-eval/queryeval/types.py
apps/query-server/queryserver/main.py
apps/query-server/queryserver/util.py
apps/query-ui/queryui/Sycamore_Query.py
apps/query-ui/queryui/ntsb.py
apps/query-ui/queryui/util.py
lib/sycamore/sycamore/query/planner.py
lib/sycamore/sycamore/query/schema.py
lib/sycamore/sycamore/tests/integration/query/test_planner.py
lib/sycamore/sycamore/tests/unit/query/test_planner.py
lib/sycamore/sycamore/tests/unit/query/test_schema.py

Not yet done but this is what I'm proposing to make the OpenSearchSchema more flexible.

Make OpenSearchSchema a proper Pydantic model.

---

apps/query-eval/queryeval/driver.py
apps/query-eval/queryeval/types.py

Verified with internal config yamls

Accept query plan examples in config

---

apps/query-eval/queryeval/driver.py
apps/query-eval/queryeval/types.py
lib/sycamore/sycamore/query/operators/top_k.py

1. Tested on local results files
2. Update TopK operator to be consistent with docset.top_k

Add plan correctness metrics summary + K in TopK optional

---

lib/sycamore/sycamore/tests/unit/transforms/test_partition.py

failed in three consecutive PRs
#944 
#954 
#955

skip flaky test

---

lib/aryn-sdk/aryn_sdk/partition/partition.py

In response to customer issue via email.

Work around hang observed during vcrpy recording.

---

apps/query-eval/queryeval/driver.py

Fixed query tag check

---

lib/aryn-sdk/aryn_sdk/partition/partition.py

Makes https://github.com/aryn-ai/sycamore/pull/976 available via the SDK

Add Enhance Table Option to SDK

---

lib/sycamore/sycamore/transforms/detr_partitioner.py
lib/sycamore/sycamore/utils/cache.py
lib/sycamore/sycamore/utils/time_trace.py

Work around lack of resource module on Windows.

---

lib/sycamore/sycamore/data/table.py
lib/sycamore/sycamore/transforms/merge_elements.py
lib/sycamore/sycamore/transforms/split_elements.py

1. Add a "column_headers" field to the table element, to store the column headers.
2. While Splitting elements for tables, split at a new line character, and attach column headers and other metadata to table chunk.

Add table-chunker

---

lib/sycamore/sycamore/tests/unit/utils/test_bbox_sort.py
lib/sycamore/sycamore/utils/bbox_sort.py

Don't put page-footers in columns regardless of whether theyre in a column

Don't try to put footers in columns

---

apps/query-eval/queryeval/driver.py
apps/query-eval/queryeval/test-results.yaml
apps/query-eval/queryeval/test_driver.py
apps/query-eval/queryeval/types.py

Tested with test
This metric only considers recall and doesn't have a capped N

Add expected documents in query-eval tool

---

lib/sycamore/sycamore/connectors/file/file_writer.py
lib/sycamore/sycamore/data/table.py
lib/sycamore/sycamore/tests/unit/data/test_table.py

lets `docset.write.json()` work when table extraction is on.
forgive the mypy shenanigans

enable JSONifying tables

---

lib/sycamore/sycamore/llms/prompts/__init__.py
lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/tests/unit/transforms/test_extract_table_properties.py
lib/sycamore/sycamore/transforms/extract_table_properties.py

Making following changes
1. Adding one shot prompting 
2. Adding table image to the llm request for better key-value identification 
3. Reducing the total number of LLM request to one for each table.

adding one shot prompting along with multimodal request

---

apps/query-eval/queryeval/driver.py

Removed the duplicate code that was executing the query twice.

Removed duplicate code in query execution.

---

lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/transforms/extract_table_properties.py

Changes:
1. Updated the prompt to support key-value tables where all keys are set to null.
2. Fixed a bug causing the raw_answer variable to reset improperly.

extract table properties prompt & bug fix

---

lib/sycamore/sycamore/query/execution/sycamore_operator.py
lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_operator.py

Flag based control for vectorsearch result reranking

disable vectorsearch rerank by default in query

---

notebooks/elasticsearch-writer.ipynb

There's some extra diff here from how my notebook is structured, don't think it should affect execution.

Rename Embedding in ElasticSearch Notebook

---

lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
lib/sycamore/sycamore/connectors/opensearch/opensearch_writer.py
lib/sycamore/sycamore/query/client.py
lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_html_to_opensearch.py
lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_opensearch_read.py
lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_pdf_to_opensearch.py
lib/sycamore/sycamore/tests/integration/query/conftest.py
lib/sycamore/sycamore/tests/integration/query/execution/test_sycamore_query.py

No pagination for KNN queries.

Disable use of scroll in OpenSearch reader when running KNN queries.

---

docs/source/sycamore/APIs/low_level_transforms/merge_elements.rst
lib/sycamore/sycamore/transforms/merge_elements.py

Also fixed up the docstring to make it look prettier in rtd

add TableMerger to merge elements docs

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/tests/unit/test_docset.py

Modified LLM filter to combine elements up til token limit to make fewer LLM calls. (Previously 1 call per element)

Merge-elements-LLM-filter

---

lib/sycamore/sycamore/tests/unit/transforms/test_embed.py
lib/sycamore/sycamore/transforms/embed.py

Delay initializing openai client in embedder

---

lib/sycamore/sycamore/tests/unit/query/test_planner.py
lib/sycamore/sycamore/tests/unit/transforms/test_schema.py
lib/sycamore/sycamore/transforms/extract_schema.py

Support some basic type casting. I think we'll want "typed types" eventually and also some column standardization plugins, but I don't want to block on API design

Property extraction type cast

---

.github/workflows/dependency-review.yml

Checks for insecure dependencies and fails the PR if any have been added.

Add Dependency Review Action

---

lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

To fix deprecated cryptography warnings.

Bump PyPDF

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/llms/prompts/prompts.py
lib/sycamore/sycamore/tests/unit/test_docset.py
lib/sycamore/sycamore/tests/unit/transforms/test_schema.py
lib/sycamore/sycamore/transforms/__init__.py
lib/sycamore/sycamore/transforms/extract_schema.py
lib/sycamore/sycamore/utils/extract_json.py

behavioral change:
now puts extracted properties in the property keyed by the name of the entity extracted

[llm unify 4/n] extract properties

---

lib/sycamore/sycamore/tests/unit/test_materialize.py

Using patch for mocking instead of modifying class method. Dunno why it took a day to show up in GH.

Reliability mocking bug

---

lib/sycamore/sycamore/llms/prompts/__init__.py
lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/llms/prompts/jinja_fragments.py
lib/sycamore/sycamore/llms/prompts/prompts.py
lib/sycamore/sycamore/tests/unit/llms/test_llms.py
lib/sycamore/sycamore/tests/unit/test_docset.py
lib/sycamore/sycamore/tests/unit/transforms/test_extract_entity.py
lib/sycamore/sycamore/tests/unit/transforms/test_llm_filter.py
lib/sycamore/sycamore/transforms/extract_entity.py

Also refactors entity extractor to break up the megafunction

[llm unify 5a/n] Add JinjaPompt and re-convert extract entities

---

lib/sycamore/sycamore/query/client.py
lib/sycamore/sycamore/query/planner.py

Add planner interface

---

lib/sycamore/sycamore/writer.py

Use isinstance for inheritance.

Writer Reliability bug

---

lib/sycamore/sycamore/llms/gemini.py

Changes to stable versions, or if not available, a generalized experimental one.

Change Gemini Model Names

---

apps/remote-processor-service/poetry.lock
apps/remote-processor-service/pyproject.toml
lib/remote-processors/poetry.lock
lib/remote-processors/pyproject.toml

Fixes final dependabot errors.

Fix Final Errors

---

lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/transforms/llm_filter.py

1. Change validate when you want to filter on a document property and do not need chunking.
2. Allow chunking when you want to use a field from elements that is similar to text representation.

Llm filter bugs

---

lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

Fixes: https://github.com/aryn-ai/sycamore/security/dependabot/346

Bump Torch to Fix Critical Vulnerability

---

lib/sycamore/sycamore/connectors/aryn/ArynWriter.py
lib/sycamore/sycamore/writer.py

also put the api calls in a session to share a tcp connection between calls. it seems to help a little

add autoschema param for aryn writer

---

lib/sycamore/sycamore/tests/unit/transforms/test_spread_properties.py
lib/sycamore/sycamore/transforms/spread_properties.py

if everything has to go into properties.entity this is a requirement

spread property data, not references

---

lib/sycamore/sycamore/connectors/file/file_scan.py

[Function definition](https://github.com/aryn-ai/sycamore/blob/1f68ba5d449cb0be806bd8e52fc12cde0531fc0d/lib/sycamore/sycamore/materialize.py#L221)

Fix var name for MRR which broke on bad merge

---

lib/sycamore/sycamore/query/execution/sycamore_executor.py

I was reading through some code and felt an urge to "tidy up".

Miscellaneous code-level improvements.

---

lib/sycamore/sycamore/query/execution/sycamore_operator.py
lib/sycamore/sycamore/tests/unit/query/conftest.py
lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_executor.py
lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_operator.py

Don't include original_elements in queries

---

lib/sycamore/sycamore/llms/openai.py
lib/sycamore/sycamore/llms/prompts/default_prompts.py
lib/sycamore/sycamore/tests/integration/transforms/test_llm_filter.py

1. Revert the prompt -> test_llm_filter fails
2. Change the model to gpt-4.1-mini -> test_llm_filter passes.

Add a new OpenAI model, revert LlmFilterPrompt change

---

lib/sycamore/sycamore/llms/gemini.py

Was getting no content back for the planner. This change would have given me a pointer as to what was going wrong.

Add debugging for unexpected gemini model stop reasons.

---

lib/sycamore/sycamore/llms/config.py

Includes Claude 4 and some bumps to other model versions.

Update LLM models

---

lib/sycamore/sycamore/tests/unit/transforms/test_table_extractor.py
lib/sycamore/sycamore/transforms/table_structure/extract.py

This should also address the NoneType is not iterable exception we have been seeing.

Add retries for VLMTableStructureExtractor.

---

lib/sycamore/sycamore/connectors/doc_reconstruct.py
lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py

* Implemented document reconstruction class for rag mode.
* Updated abstraction of the parent class.

Add support for document reconstruct for RAG.

---

lib/sycamore/sycamore/tests/unit/transforms/test_clustering.py

Bring in back Alex's flaky fix.

Fix test clustering flaky

---

.gitignore
notebooks/ArynPartitionerPython.ipynb
notebooks/metadata-extraction.ipynb

ArynPartitionerPython: We changed where config was stored, and somewhat changed the output.
metadata-extraction: We completely changed how entity extraction worked. roughtly entity ->
FlightAccidentReport, but it was somewhat more involved.

Fix notebook tests.

---

apps/integration/poetry.lock
apps/jupyter/poetry.lock
apps/remote-processor-service/poetry.lock
lib/poetry-lock/poetry.lock
lib/poetry-lock/pyproject.toml
lib/remote-processors/poetry.lock
lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

Addreses vuln: https://github.com/aryn-ai/sycamore/security/dependabot/386

Upgrade dependency on requests

---

lib/sycamore/sycamore/materialize.py

Do not count metadata documents when refreshing MRR

Fix MRR refresh

---

apps/integration/poetry.lock
apps/integration/pyproject.toml

I missed the integration app in my previous commit.

[Dependency] Upgrade urllib3 in one more app.

---

lib/sycamore/sycamore/transforms/text_extraction/ocr_models.py
lib/sycamore/sycamore/utils/pdf.py

Add Optional Parameters 

---

lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

Updates the pyproject version to help with downstream upgrades.

Bump Pillow

---

lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

Upgrades Paddle to 3.1, which allows for a new model to be brought in.

Bump Paddle to 3.1

---

lib/sycamore/sycamore/transforms/clustering.py

Ray complains the intermediate tuple representation when doing groupby for K-Means, switch to a dict.

Fix warning for K-Means

---

apps/integration/poetry.lock
apps/jupyter/poetry.lock
apps/remote-processor-service/poetry.lock
lib/poetry-lock/poetry.lock
lib/poetry-lock/pyproject.toml
lib/remote-processors/poetry.lock
lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

https://github.com/aryn-ai/sycamore/security/dependabot/422

Upgrade aiohttp dependency

---

lib/sycamore/sycamore/connectors/opensearch/sync.py
lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_sync.py

* for oss-*.md files, still clean them up; oss intends to own those
* For *.md files, the deletion was a bug, we don't want to remove other md documents
* For other unrecognized file; we just keep them around since we can ignore them anyway.

Tolerate mis-formatted files instead of cleaning up.

---

lib/sycamore/sycamore/connectors/aryn/ArynWriter.py

Fix `ArynWriter`'s use of stream

---

lib/sycamore/sycamore/docset.py
lib/sycamore/sycamore/llms/gemini.py
lib/sycamore/sycamore/llms/llms.py
lib/sycamore/sycamore/llms/openai.py
lib/sycamore/sycamore/tests/integration/transforms/test_data_extraction.py
lib/sycamore/sycamore/tests/unit/llms/test_llms.py
lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_extract.py
lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_strategy.py
lib/sycamore/sycamore/transforms/aggregation.py
lib/sycamore/sycamore/transforms/property_extraction/extract.py
lib/sycamore/sycamore/transforms/property_extraction/prompts.py
lib/sycamore/sycamore/transforms/property_extraction/strategy.py
lib/sycamore/sycamore/utils/llm_utils.py

handle lists, add utils for seeing llm utilization, add schemaUpdateStrategy interface, image prompting ability

[extract] various improvements

---

lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_attribution.py
lib/sycamore/sycamore/transforms/property_extraction/attribution.py
lib/sycamore/sycamore/transforms/property_extraction/prompts.py

Make the system prompt a little more robust
Make attribution work when element indices are non-consecutive (no index-out-of-bounds)

[extract] misc fixes

---

lib/sycamore/sycamore/schema.py
lib/sycamore/sycamore/tests/unit/test_schema.py

Previously we were not correctly serializing custom types in the old style.

Fix one additional test case with schema serialization.

---

lib/sycamore/sycamore/schema.py

This improves backwards compability.

Default array item_type to string.

---

lib/sycamore/sycamore/schema.py
lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_prompts.py
lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_strategy.py
lib/sycamore/sycamore/transforms/property_extraction/extract.py
lib/sycamore/sycamore/transforms/property_extraction/prompts.py
lib/sycamore/sycamore/transforms/property_extraction/strategy.py

At the moment I've hooked it into the update_schema traversal. It should really get its own traversal though (that will let me do things like retry). See previous points about abstracting that and getting confuddled

[Extract] Add validators

---

lib/sycamore/sycamore/tests/integration/transforms/property_extraction/test_schema_extract.py
lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_schema_extract.py
lib/sycamore/sycamore/transforms/property_extraction/extract.py
lib/sycamore/sycamore/transforms/property_extraction/merge_schemas.py
lib/sycamore/sycamore/transforms/property_extraction/utils.py

* Fixes the bug in _process_schema_fields in merge_schemas.py which occurred because we changed the output format received from LLM.
* Remove create_named_property method from utils.py

Fix merge logic in suggest schema.

---

lib/sycamore/sycamore/llms/prompts/__init__.py

importing default_prompts causes us to construct a whole bunch of prompt instances at import time
unit tests passed but this might break some stuff. I hope not.

faster import

---

apps/integration/poetry.lock
apps/jupyter/poetry.lock
apps/remote-processor-service/poetry.lock
lib/poetry-lock/poetry.lock
lib/poetry-lock/pyproject.toml
lib/remote-processors/poetry.lock
lib/sycamore/poetry.lock
lib/sycamore/pyproject.toml
poetry.lock

Addresses https://github.com/aryn-ai/sycamore/security/dependabot/437

[Dependencies] Upgrade authlib.
