aryn-ai/sycamore

- sycamore/tests/conftest.py
- sycamore/tests/unit/transforms/test_partition.py
- sycamore/transforms/partition.py
Modify UnstructuredPdfPartitioner to inherit parent document properties down to child elements.  For now, just "path", but extensible.  This allows properties to be directly available in search results without the complication and expense of retrieving the parent document.
> UnstructuredPdfPartitioner to inherit parent properties

- sycamore/reader.py
- sycamore/scans/file_scan.py
- sycamore/tests/integration/test_html_to_opensearch.py
- sycamore/tests/unit/scans/test_binary_scan.py
This change adds a file-level metadata provider. The provider is invoked for each "document" read by BinaryScan and it's returned dictionary is merged with the element properties. The first metadata provider just reads from a JSON file where properties are keyed by the filePath. This allows us to build workflows against simple crawler results.
```
s3://mybucket/directory/
...TencentSort2016.pdf
...ExoshuffleCloudSort2022.pdf
...file3.pdf
...manifest.json
```
manifest.json would look like:
```json
{
"s3://mybucket/directory/TencentSort2016.pdf": {
"remote_url": "http://sortbenchmark.org/TencentSort2016.pdf",
"indexed_at": "2023-10-04 and some time"
},
"s3://mybucket/directory/file2.pdf": {
"remote_url": "http://sortbenchmark.org/ExoshuffleCloudSort2022.pdf",
"indexed_at": "2023-10-04 and …
```
> Add FileMetadataProvider

- sycamore/transforms/embed.py
When SentenceTransformer embed a batch of sentences, and the first sentence happens to be None, an exception for subscripting None is thrown. We do an easy fix to convert None to empty string for now.
Closes #73
> Fix bug of SentenceTransformer exception for subscripting None

- .readthedocs.yaml
- docs/requirements.txt
- pyproject.toml
Followed instructions here https://stackoverflow.com/a/64700797 to install the module so that autodoc can pick up the definitions on RTD. You can see a preview here: https://sycamore.readthedocs.io/en/rtd/index.html. I will take down docs for this branch once we merge this commit.
> Update the doc building process for RTD

- .github/workflows/testing.yml
- .pre-commit-config.yaml
- notebooks/tutorial.ipynb
- poetry.lock
- pyproject.toml
This commit pulls in nbmake as a dependency so that we can automatically test the code in Jupyter notebooks for regressions. You can run tests using
poetry run pytest --nbmake notebooks/*.ipynb
This will excecute each cell of the notebooks and ensure they run without error. It does not do any kind of corectness checking.
Notebooks typically cover end-to-end scenarios, so these tests are effectively integration tests, and they require, for example, and OpenAI API key and local OpenSearch instance. For this reason they are not run automatically during pre-commit. Instead, I've added them as another step in the integration test GitHub workflow.
These tests exposed some errors in tutorials.ipynb, which are also fixed in this commit.
Finally this commit adds a pre-commit step that strips …
> Add notebook tests and utilities to strip output from notebooks.

- examples/simple_ingest.py
- sycamore/docset.py
- sycamore/tests/unit/transforms/test_partition.py
- sycamore/tests/unit/transforms/test_spread_properties.py
- sycamore/transforms/__init__.py
- sycamore/transforms/partition.py
- sycamore/transforms/spread_properties.py
The new SpreadProperties transform copies properties from a Document to its Elements.  This denormalization can be useful to provide efficient access to the properties from the retrieved documents at search time.  The current use is for 'title' and 'path' in examples/simple_ingest.py.  Its use is optional.
This supersedes the previous code in the PDF partitioner that inherited the path from parents.  A unit test is included.
> Transform to denormalize specified properties from parents to children

- README.md
Same style as examples/simple_ingest.py
> Fix bug in README.md; opensearch function expects kwargs.

- sycamore/transforms/partition.py
ocr_languages is deprecated and being replaced with languages.
I debated whether to go to the trouble of still supporting ocr_languages for compatibility reasons. Given that few people are likely to be using this, I opted not to make the code more complex by supporting both options, but happy to change if people feel strongly -- it's not a big deal either way.
> Update partion_pdf paramters to match Unstructured.

- README.md
- pyproject.toml
Also adds a badge in the Readme.
> Update pyproject.toml to exclude 3.12 from list of python version.

- poetry.lock
Other changes to the lock file automatically happen when running poetry lock --no-update
Error was:
Warning: The locked version 2.0.0 for executing is a yanked version. Reason for being yanked: Released 2.0.1 which is equivalent but added 'python_requires = >=3.5' so that pip install with Python 2 uses the previous version 1.2.0.
> Re-lock poetry config to fix a warning around the 'executing' package.

- docs/source/APIs/transforms/random_sample.rst
- docs/source/APIs/transforms/transforms.rst
- sycamore/docset.py
- sycamore/tests/unit/transforms/test_random_sample.py
- sycamore/transforms/__init__.py
- sycamore/transforms/random_sample.py
This utilizes the underlying dataset.random_sample to randomly sample from a DocSet. Useful for tests and experiments.
Still trying to figure out a potential issue with the the documentation generation, but the functionality is working for me.
> Add random_sample transformation.

- opensearch/Dockerfile
- opensearch/README.md
- opensearch/aryn-opensearch.sh
- opensearch/opensearch.yml
In particular, the aryn-opensearch.sh script sets up all of the opensearch configuration necessary to let the Aryn demo UI work. It also coordinates with the importer to make sure that the importer only starts when opensearch is ready.
> Add the scripts to dockerize opensearch in a way that works with the other sycamore components

- docker_compose/compose.yaml
- importer/docker-poetry-packages.sh
compose.yaml: remove the shm setting -- testing indicates there's no useful default and it could
cause problems on small memory machines
docker-poetry-packages.sh: install the sycamore packages since the script limits installation
> Fix bug in dockerization from merge

- pyproject.toml
This is necessary to ensure that the sycamore library remains installable with pip.
> Move library dependencies back under [tool.poetry.dependencies]

- crawler/http/Dockerfile
- crawler/http/run-crawler.sh
Avoid installing the sycamore library because it is large (GB) and unneeded.
Add the build stamp environment variables and logging we're adding to the other containers.
> Fixup dockerization -- skip sycamore library & add build-stamps

- importer/docker_local_import.py
30 is too small to get good results.
512 crashes with a too large context window importing the sort benchmark.
> Change the default merge size to 256.

- crawler/http/crawler/settings.py
- crawler/http/crawler/spiders/sycamore.py
- crawler/http/run-crawler.sh
You used to need to specify both a url and a domain, but we can infer the likely domain from the URL, so avoid needing to write it twice.
Also add support for a prefix check so people can download only a specific sub-tree.
> Simplify running the http crawler.

- examples/s3_ingest.py
- examples/simple_ingest.py
The GTE-small embedding model is superior to MiniLM, yielding better relevance in retrieval.
> Change simple_ingest and s3_ingest to use GTE-small embedding model.

- examples/html_ingest.py
- examples/s3_ingest.py
- examples/simple_ingest.py
- importer/docker_local_import.py
- sycamore/llms/llms.py
- sycamore/tests/integration/test_pdf_to_opensearch.py
OpenAI deprecation is occuring on 1/4. To provide some level of compatibility we automatically switch the model with a warning if the caller passes in the deprecated model.
> Migrate from text-davinci-003 to gpt-3.5-turbo-instruct.

- sycamore/docset.py
- sycamore/tests/unit/test_docset.py
This commit adds the `with_property`, `with_properties`, and `map_elements`. This are primarily syntactic sugar around map operations that I have found to be useful when writing complex scripts. The `with_property` and `with_properties` methods simplify adding properties to each Document in the in the DocSet. They are loosely modeled after similar methods on Spark Datasets.
The `map_elements` method applies a function to each element in each Document in the DocSet. This is a thin wrapper around the Document-level `map` operation, but helps reduce boilerplate.
> Add some useful utility methods for DocSets.

- examples/simple_ingest.py
- sycamore/data/document.py
- sycamore/functions/rabin_karp.py
- sycamore/functions/simhash.py
- sycamore/tests/unit/functions/test_rabin_karp.py
- sycamore/tests/unit/functions/test_simhash.py
- sycamore/tests/unit/transforms/test_sketcher.py
- sycamore/transforms/__init__.py
- sycamore/transforms/sketcher.py
- sycamore/writers/opensearch.py
No longer using SimHash by default, but code is still available.  Shingles are now one-dimensional.  Speed is improved.  Accuracy is better, without bizarre false positives.  SketchDebug added to show actual de-duped pairs.  Parameter space is reduced from 4 to 3 dimensions and defaults are tuned for the current state of the algorithm.  Overall, this looks like a substantial improvement.
> Use classic shingles; simplified implementation; added debug; re-tuned

- .github/workflows/testing.yml
- notebooks/metadata-extraction.ipynb
- sycamore/tests/integration/query/test_query_opensearch.py
Current default OS 2.9 is old and doesn't have hybrid search. 2.11 seems to have an http client issue which requires some additional config, but 2.12 seems to go back to 2.9 behavior. Keeping it 2.10 until we go to 2.12
> Upgrade test workflow to os 2.10

- crawler/http/Dockerfile
- crawler/s3/Dockerfile
- docs/source/data_ingestion_and_preparation/running_a_data_preparation_job.md
- docs/source/tutorials/conversational_memory_with_langchain.md
- docs/source/tutorials/sycamore-jupyter-dev-example.md
- examples/simple_config.py
- importer/docker_local_import.py
- jupyter/Dockerfile
- jupyter/run-jupyter.sh
- notebooks/default-prep-script.ipynb
- notebooks/jupyter_dev_example.ipynb
- opensearch/Dockerfile
- opensearch/config.yml
- opensearch/opensearch.yml
- opensearch/roles_mapping.yml
- opensearch/sycamore-opensearch.sh
Using self-generated, self-signed certificates.  No longer using mini HTTP server for signaling; using OpenSearch cluster metadata instead.
> Quickstart: use SSL for all network communication: OpenSearch and Jupyter

- opensearch/2.11/Dockerfile
- opensearch/2.11/README.md
- opensearch/2.11/opensearch.yml
- opensearch/2.11/sycamore-opensearch.sh
- opensearch/Dockerfile
- opensearch/sycamore-opensearch.sh
1. upgrades opensearch to 2.12
a. Lets us turn of the feature flags
b. except that the rag pipeline feature flag is a little bugged, so we have to do this flick operation
2. stores the 2.11 stuff in opensearch/2.11/
a. not sure if this is necessary but felt like it might be useful to keep a copy around per version.
will want to follow the merging of https://github.com/aryn-ai/demo-ui/pull/18
> Upgrade opensearch to 2.12

- jupyter/Dockerfile
- jupyter/run-jupyter.sh
Avoid complaints from browsers about self-signed certificates.
Set SSL=1 for HTTPS
Set SSL=0 for HTTP
Docker build defaults to SSL=0
> By default, disable SSL for Jupyter, to avoid browser cert complaints.

- sycamore/evaluation/datasets.py
- sycamore/evaluation/metrics.py
- sycamore/evaluation/pipeline.py
- sycamore/tests/integration/evaluation/test_datasets.py
- sycamore/tests/integration/evaluation/test_pipeline.py
- sycamore/tests/unit/evaluation/test_metrics.py
- sycamore/transforms/query.py
This change let's you handle input datapoints where there are multiple page numbers. It returns 2 types of page_recall metrics, 1 where all pages are retrieved, and 1 where there is partial success.
> Improve recall metrics

- crawler/http/tests/http_crawler_integration.sh
Emit an error if something is already running on the port we use.
> Improve http integration test debugging.

- opensearch/sycamore-opensearch.sh
This handles a number of errors we were previously failing on
- when using both torch script and onnx models, funky pytorch internal methods get into a bad state and crash. Only use ONNX.
- when restarting the node, models are often redeployed automatically. Check that they are not deployed before trying to deploy them again (in sp_setup_transient)
- sometimes the deploy task fails due to ml memory circuit breaker tripping. Detect this, wait a couple seconds for GC to run, and then try again
- sometimes the deploy task fails due to duplicate deploy task. Detect this and watch the task we should be watching. If there is no running task, try to deploy again.
Note: We still don't handle the case where the memory circuit breaker trips during the register step
Another note: There's some …
> Increase default model deployment stability

- opensearch/sycamore-opensearch.sh
It takes 12/15 on my laptop semi-regularly, and we want to have a bit more headroom for people on slower machines.
> Bump opensearch ssl startup wait time to 30 tries.

- sycamore/evaluation/__init__.py
- sycamore/evaluation/data.py
- sycamore/evaluation/metrics/__init__.py
- sycamore/evaluation/metrics/generated_answer.py
- sycamore/evaluation/metrics/retrieval.py
- sycamore/evaluation/pipeline.py
- sycamore/functions/tokenizer.py
- sycamore/tests/integration/evaluation/test_pipeline.py
- sycamore/tests/unit/evaluation/test_metrics.py
1. Moved metric implementations to separate classes
2. Use `os_config` to configure opensearch query parameters. `os_client_args` are client configs we send directly to opensearch-py
3. Add OpenAI tokenizer
> Cleanup metrics classes + bug fixes

- compose.yaml
- notebooks/default-prep-script.ipynb
- notebooks/jupyter_dev_example.ipynb
- sycamore/docset.py
* Pass SSL env var in via docker so people could enable SSL.
* Update jupyter dev example to truncate content and limit output -- running the notebook was getting tons of output.
* Update jupyter dev example to print the right URL.
* Update show operation in docset to not show binary in elements and truncate content in elements if we would do that in the main document. Slightly refactor to avoid duplicated code.
> Fix notebooks -- proper protocol, truncate output.

- opensearch/Dockerfile
ml-commons figures out its onnxruntime dependency by looking at the operating system at build time, which doesn't quite do the correct thing, which in turn makes onnx fail on arm.
this pr fixes that, though we probably need to make it a less hacky fix
> build ml-commons locally with correct dependencies

- compose.yaml
since we think we have m1 mac working again we can remove this
> unset default opensearch platform

- opensearch/Dockerfile
this builds and adds the RPS plugin to the opensearch dockerfile so it can use the RPS image once that gets published.
We may also want to add to the default pipeline definitions, but that can wait for @alexaryn to figure out what's going on with NDD stuff
> build and install remote processor plugin in opensearch dockerfile

- sycamore/tests/integration/evaluation/test_datasets.py
This matches what we do in other integ tests and makes sure the pickled representation of the function has the absolute path to the module so that it can be imported.
> Fix integ test import error.

- notebooks/jupyter_dev_example.ipynb
This makes it easier to run the notebook integration tests locally and in Github Actions.
> Change notebook working directory when running outside container.

- .github/workflows/testing.yml
- lib/sycamore/sycamore/llms/openai.py
looking at the integ test runs in the gh action it seems to be downloading this package now at runtime - this had caused some issues before, so let's pre-download it like we do with punkt
> add averaged_perceptron_tagger to nltk downloads

- apps/opensearch/setup_models.py
- apps/opensearch/sycamore-opensearch.sh
creates a dummy conversation and interaction and then deletes them as part of starting up opensearch for the first time, forcing the creation of those indices to prevent index-not-found errors when the ui does searches against them
> initialize messages index on startup

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/partition.py
Previously the segmenetation model required a CUDA-comatible GPU, but that has changed. This commit simply removes the check that failed if no such gpu was found.
> Make SycamorePartitioner runnable on CPUs.

- apps/opensearch/Dockerfile
I think this will make docker actually check the sha that it's pulling from github to decide whether it's seen this before.
I think that in the `RUN git clone ...` state, docker saw that, said "I already did that", and used the cached result, which is fine until the git head changes underneath
> use ADD instead of RUN git clone to checkout git repos

- .github/workflows/linting.yml
- lib/sycamore/sycamore/transforms/detr_partitioner.py
Since the refactor, I've noticed that the Github actions mypy check was not catching all the mypy issues that I got when running `poetry run mypy .` locally. I believe it is the explicit-package-bases flag. Since we have __init__.py files in our main packages, we shouldn't need it, and it seems to be messing up the module path discovery.
> Remove mypy --explicit-package-bases flag and fix issues.

- apps/crawler/crawler/s3/crawler/s3_crawler.py
- apps/crawler/crawler/s3/tests/unit/test_s3_crawler.py
This is needed for the NDD blog post very soon.  It allows the crawling of public S3 buckets without AWS credentials.
> Added -anon switch to S3 crawler for public buckets.

- docs/source/index.rst
- docs/source/querying_data/remote_processors.md
There are a couple missing links still
> add docs for RPS

- apps/jupyter/Dockerfile.buildx
- apps/jupyter/profile
Without this, terminals need to do poetry run python to get things like pytesseract
> Add .profile to container so that we get poetry python not container python

- lib/sycamore/sycamore/tests/integration/textractor/test_textractor.py
- lib/sycamore/sycamore/transforms/extract_table.py
Store the entire DocumentAnalysis json response from Textract instead of our parsed Table objects. This lets you use the textractor interface to access fields we hadn't previously used in a typed way (e.g. individual row elements).
I validated this by running the following on a single doc:
1. regular TextractTableExtractor
2. CachedTextractTableExtractor for the first time
3. CachedTextractTableExtractor for the second time
We can likely add integration tests validating that caching is working but I don't want to combine it here.
> Cache entire Amazon Textract response

- apps/demo-ui/ui/src/Doclist.tsx
If we're not in ntsb setting and we didn't extract a title entity in our ingest, we get a "properties.entity is undefined" when reading properties.entity.accidentNumber
This fixes that so if properties.entity is undefined then we set the title to "Untitled"
> fix ui error when no title is extracted and we're not in ntsb setting

- apps/demo-ui/run-ui.sh
- apps/jupyter/run-jupyter.sh
- compose.yaml
To test, put two files in apps/jupyter/bind_dir:
- hostcert.pem
- hostkey.pem
Then, run like:
- VERSION=test SSL=1 docker compose up
Jupyter and the UI should come up with the specified certificate, probably still with a warning, as we're not using fully-qualified domain names yet.
> Bind mount to convey SSL cert/key to Jupyter & UI

- apps/importer/Dockerfile.buildx
- apps/jupyter/Dockerfile.buildx
Also add check to Dockerfile to make sure that remains true.
> Use chown in our copy commands to make sure all files are owned by app

- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
This matches the behavior of Document and fixes issues serializing exploded elements for OpenSearch.
> Store element bbox as a tuple rather than BoundingBox.

- lib/sycamore/sycamore/tests/unit/transforms/test_partition.py
- lib/sycamore/sycamore/transforms/partition.py
Seems the problem of below
```
<div><span>hello</span></div><div><span>world</span></div> ->
"helloworld" instead of "hello" "world"
```
is due to no separator is added when concatenate string when getting text
> Fix malformed text from beautiful soup.

- lib/sycamore/sycamore/data/document.py
This was broken when we switched to using create_element.
> Handle deserializing JSON documents when elements is None.

- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
This happens when the DETR partitioning model finds a table, but the table structure extraction model does not identify rows or columns.
This change simple leaves the TableElement as is and sets the table attribute to be None.
> Set table object to None when no table is found.

- lib/sycamore/sycamore/transforms/explode.py
I managed to get a bunch of docs with non-unique uuids post-explode, e.g.
```
fd9b2074-130f-11ef-a237-3a049e7f7082
fd9b2164-130f-11ef-a237-3a049e7f7082
fd9b2196-130f-11ef-a237-3a049e7f7082
...
```
Not sure how that happened, but this aims to make sure that the uuid1 function always has a different input. If we overflow the counter then we've pigeonholed ourselves anyway
> ensure unique uuids post explode via sequence numbers

- lib/sycamore/sycamore/transforms/partition.py
Looks like the driver/worker process model ser/de incompatible, move model instantiation inside worker process to get rid of the ser/de.
```
RuntimeError: Attempting to deserialize object on a CUDA device but
torch.cuda.is_available() is False. If you are running on a CPU-only
machine, please use torch.load with map_location=torch.device('cpu')
to map your storages to the CPU.
```
> Fix model deserialization error

- .github/workflows/testing.yml
The ndd_example notebook relies on data being loaded, so it doesn't make sense to run every time. This change explicitly lists all the notebooks to test and omits that one.
> Explicitly enumerate notebooks to automatically test.

- lib/sycamore/sycamore/transforms/explode.py
uuid1().is_safe returns unknown on Mac, and it's posible that concurrent calls may produce collisions on the same host. This change just switches to uuid4 (random uuids) to reduce this risk.
> Switch from uuid1() to uuid4() in explode.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/partition.py
Adds client side code to use a remote model server.  When a the parameter `model_server_endpoint` is specified to `SycamorePartitioner` or `DeformableDetr.infer`, it will attempt to use the model server for acceleration; otherwise there is no change in behavior.
To use a locally running model server on port 8000 with a `SycamorePartitioner` from within a docker container: `SycamorePartitioner("Aryn/deformable-detr-DocLayNet", model_server_endpoint="http://host.docker.internal:8000/")`
Or use the `DeformableDetr` model directly: 
`from PIL import Image`
`import requests`
`example_url = "https://huggingface.co/Aryn/deformable-detr-DocLayNet/resolve/main/examples/doclaynet_example_1.png"`
`image = Image.open(requests.get(example_url, stream=True).raw)`
`d.infer((image,), 0.7, …
> Add remote model server support

- lib/sycamore/sycamore/data/table.py
- lib/sycamore/sycamore/functions/document.py
- lib/sycamore/sycamore/tests/integration/test_image_utils.py
- lib/sycamore/sycamore/utils/image_utils.py
This commit introduces a new utility function to draw a collection of boxes on a PIL image. This is used in both the DrawBoxes class and the table drawing code. In general it is useful for testing new OCR/detection methods, even when outside of DocSets.
This change should not impact existing public sycamore code.
> Refactor drawing code to support additional formats.

- lib/sycamore/sycamore/transforms/embed.py
This parameter is used by Ray to control how it batches records for map_batches. We recently added an assertion that this is a positive integer, but None and the literal string "default" are also valid options for Ray. This was causing some of our integration tests to fail.
> Adjust assertion for batch_size resource_arg.

- lib/sycamore/sycamore/functions/document.py
- lib/sycamore/sycamore/tests/integration/functions/test_document.py
There was an edge case with the previous implementation where a page with no elements would cause images and elements to be misaligned. This fixes that problem by always counting pages based on pages (images) from the pdf rather than elements.
> Fix split_and_convert_to_image when some pages have no elements.

- examples/simple_weaviate.py
- lib/sycamore/sycamore/writers/weaviate_writer.py
Weaviate autoschema will parse empty lists as lists of strings and then refuse to ingest subsequent documents that prove this assumption wrong. But empty lists don't have any meaningful information in them, so we can simply drop them entirely from the record, so weaviate will not have problems. This means we have a much easier time specifying out the problematic fields ahead of time because there aren't any.
> remove empty lists from documents in weaviate writer

- apps/timetrace/Makefile
- apps/timetrace/README.md
- lib/sycamore/sycamore/utils/time_trace.py
This is true on the Mac, for instance. Also, switch the ttviz Makefile to c++20 to be more accomodating to older compilers and add a README.
> TimeTrace: Fallback to RUSAGE_SELF when RUSAGE_THREAD isn't present.

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/functions/tokenizer.py
- lib/sycamore/sycamore/tests/unit/transforms/test_term_frequency.py
- lib/sycamore/sycamore/transforms/__init__.py
- lib/sycamore/sycamore/transforms/term_frequency.py
Creates a term frequency table transform, e.g.
```python
from sycamore.transforms.term_frequency import TermFrequency
davinci_llm = OpenAI(OpenAIModels.GPT_3_5_TURBO_INSTRUCT.value)
tokenizer = HuggingFaceTokenizer("thenlper/gte-small")
ctx = sycamore.init()
ds = (
ctx.read.binary(paths, binary_format="pdf")
.partition(partitioner=UnstructuredPdfPartitioner())
.regex_replace(COALESCE_WHITESPACE)
.extract_entity(entity_extractor=OpenAIEntityExtractor("title", llm=davinci_llm, prompt_template=title_template))
.explode()
.embed(embedder=SentenceTransformerEmbedder(model_name="thenlper/gte-small", batch_size=100))
.transform(cls=TermFrequency, tokenizer=tokenizer)
)
ds.show(limit=100, truncate_length=500)
```
```
{'properties': {'filename': '',
'filetype': 'application/pdf',
'parent_id': …
```
> add term_frequency transform

- lib/sycamore/sycamore/tests/unit/transforms/test_sketcher.py
Without the shutdown, running:
poetry run pytest lib/sycamore/sycamore/tests/unit/transforms/test_ske*.py lib/sycamore/sycamore/tests/unit/transforms/test_random_sample.py
yields:
RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'
Unclear why it's only needed here.
> Fix cross-test error

- lib/sycamore/sycamore/scans/materialized_scan.py
- lib/sycamore/sycamore/tests/unit/transforms/test_base.py
- lib/sycamore/sycamore/tests/unit/transforms/test_mapping.py
- lib/sycamore/sycamore/tests/unit/transforms/test_merge_elements.py
- lib/sycamore/sycamore/transforms/base.py
- lib/sycamore/sycamore/transforms/map.py
If you pass in a not-callable, the error message can be obscure (__name__ not found) Instead check for the property that we want that the callable is properly named.
Discovered by trying to use map + GreedyTextElementMerger.
Also verify that the names we calculate are correct. They were not before.
> Provide better error messages on *Map mis-use

- lib/poetry-lock/poetry-lock-all.sh
We haven't fixed the proxy to be consistent, so fix the script to special case that directory. Fixes issue with the poetry.lock file not being updated when it needs to be.
> Run poetry lock in openai-proxy with poetry-lock-all.sh

- lib/sycamore/sycamore/tests/integration/test_pdf_to_weaviate.py
weird inconsistencies happen because of cuda, so we'll just use unstructured here
> use unstructured in weaviate IT

- lib/sycamore/sycamore/transforms/detr_partitioner.py
This may help address disk space issues. Note that pdf2image.convert_from_bytes does internally write to a file (since it is ultimately just calling a command-line utility), but it deletes in the context of the same method.
> Remove temporary file write in DETR partitioner.

- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/tests/integration/query/test_query_opensearch.py
- lib/sycamore/sycamore/tests/integration/test_html_to_opensearch.py
- lib/sycamore/sycamore/tests/integration/test_pdf_to_opensearch.py
- lib/sycamore/sycamore/tests/unit/test_rewriter.py
- lib/sycamore/sycamore/tests/unit/writers/test_base.py
- lib/sycamore/sycamore/writer.py
- lib/sycamore/sycamore/writers/base.py
- lib/sycamore/sycamore/writers/common.py
- lib/sycamore/sycamore/writers/opensearch.py
also fixed the query tests to actually run their ingest pipeline so they don't depend on going after other opensearch ITs (which now clean up after themselves)
> convert opensearch writer to use base writer 1/3

- apps/jupyter/fixuser.py
The has the Janky `dpkg-divert` stuff to work around weird installation errors.  But, it saves 5.6GB in image size over the method in PR #448.
> Another approach to CUDA support in Docker, with less bloat.

- lib/sycamore/sycamore/utils/pdf.py
Previously, the queue is set infinity. The memory consumption positive correlates to pdf page numbers, e.g. parsing a 2k page pdf requires 8gb memory while  parsing 4k page pdf requires 16gb memory using Eri's Rss metric tool. By setting queue size to 64, the rss stays fixed at around 2gb beyond 200 pages.
This number may need sync with batch size, it seems good enough to mitigate memory pressure for now.
> Potential memory leak point

- apps/integration/integration/automation/runtests.sh
- apps/integration/integration/containers/running.py
- apps/integration/integration/containers/stack.py
- apps/integration/integration/ingests/crawler.py
- apps/integration/integration/tests/test_basic.py
- apps/opensearch/setup_models.py
Important fixes:
* Add a ludicrous amount of additional logging so it's rare that something isn't logged after a short wait.  Logs go to error because I was having some issues with info logging not showing up.  That may be fixed now, but unclear.
* rm -rf /app/.scrapy/imported /app/.scrapy/downloads instead of *; * isn't being expanded
* Fix imported files via find in the filesystem instead of parsing output. The ray output and importer output are sometimes interleaved on the same line
* Verify that the scraper downloaded something before continuing
* Tolerate missing indices on deletion
* Enable optionally waiting before aborting the test so state is preserved for inspection
* Add more debugging on the opensearch side, although bugs appeared to all be test-side.
* Update automation to …
> Get integration tests working again.

- lib/sycamore/sycamore/tests/unit/transforms/test_schema.py
- lib/sycamore/sycamore/transforms/extract_schema.py
The ExtractProperties transform relies on a schema to guide the LLM on what to extract. This schema can be extracted using an LLM, or it can be added explicitly to each documetn in a "_schema" property.
I frequently want to be able to extract fields from an explicit schema that I pass in, without having to update the properties map on each document. This change just adds that ability in the form of arguments to the OpenAIPropertyExtractor class. Example usage of how to extract basic information about a scientific paper from a DocSet:
schema = {
"title": "string",
"authors": "list[string]",
"abstract": "string"
}
docs = context.read.binary(paths=[path], binary_format="pdf")\
.partition(partitioner=SycamorePartitioner())\
.extract_properties(OpenAIPropertyExtractor(llm, …
> Make it possible to pass in a schema for property extraction.

- lib/sycamore/sycamore/connectors/weaviate/weaviate_writer.py
- lib/sycamore/sycamore/connectors/writers/common.py
- lib/sycamore/sycamore/writer.py
Weaviate nested fields don't do filters or aggregations so we add the option to flatten them to top-level 'properties'.
An 'unflatten' option should be added to the scan, prob when the pinecone scan is written.
> Add flatten option to weaviate writer

- lib/sycamore/sycamore/transforms/detr_partitioner.py
This will allow a remote call without serializing the whole TableTransformerStructureExtractor.
Also added a missing timetrace decorator.
> process_batch() defaults table_structure_extractor.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/embed.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
The following modules:
- `easyocr`
- `sentence_transformers`
- `transformers`
- `torchvision`
all pull some shennanigans with `__init__.py` whereby the mere act of importing them starts a PyTorch thread.  Aside from being rude, this has the side effect of attaching to the GPU and holding a reference count on the GPU devices in `/dev/`.  In a Ray context, we don't want the driver to use the GPU, just the workers.  Also, just generally, importing something should not be so heavy-handed.
> Don't start PyTorch thread just doing import.

- lib/sycamore/sycamore/tests/unit/transforms/test_base.py
- lib/sycamore/sycamore/transforms/base.py
Was modifying 'intermediate_datasink_kwargs' which was resulting in nested directories for each node.
> Bugfix intermediate data

- lib/sycamore/sycamore/tests/unit/test_docset.py
- lib/sycamore/sycamore/transforms/map.py
Based on the ordering of params, we're unable to inject a custom name into a Map node. This fixes the order
> Allow custom names for Map/FlatMap nodes

- docs/source/data_ingestion_and_preparation/connector_support.md
- docs/source/data_ingestion_and_preparation/connectors.rst
- docs/source/data_ingestion_and_preparation/connectors/weaviate.md
- docs/source/index.rst
The compose file looks big here, but it's in a collapsible and looks like this by default:
also adds to the ToC like so
```
Data Ingestion and Preparation
..
..
Transforms     v
Connectors     ^
DuckDB
Weaviate
```
> add weaviate writer docs. Also add connectors to ToC

- lib/sycamore/sycamore/tests/integration/evaluation/test_datasets.py
Fixes the broken integration test caused by `PatronusAI/FinanceBench` being removed from Huggingface. Note, since this test tests loading from Huggingface, continuing with another instance of FinanceBench wouldn't work well. I have chosen to replace this dataset with `truthfulqa/truthful_qa` from HuggingFace that's not large and has similar properties.
> Fix broken Dataset Integration Test

- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/tests/unit/data/test_document.py
instead of whatever text representation it would ordinarily be. Can set it to something else if needed tho with just `table.text_representation = 'blah'`
> set table text rep to csv rep of table

- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/data/element.py
This is helpful for debugging as it does not dump the entire contents of, e.g., embedding and shingles.
> Add __str__ methods to Document and Element.

- lib/sycamore/sycamore/utils/http.py
Example use:
```
c = OneShotKaClient("https://test-api.foo.com/v1/magic")
tok = "ey...AQ"
hdr = {"Authorization": f"Bearer {tok}"}
form = {
"options": '{"use_foo": true}',
"pdf": "@files/doc.pdf",
}
buf = c.post(headers=hdr, form=form)
print(buf)
print(c.resp.status, c.resp.getheaders())
```
> HTTP client that acts more like curl.

- examples/simple_duckdb.py
- lib/sycamore/sycamore/__init__.py
- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/tests/integration/connectors/duckdb/test_pdf_to_duckdb.py
- lib/sycamore/sycamore/tests/integration/transforms/test_partition.py
- lib/sycamore/sycamore/tests/unit/transforms/test_aryn_partitioner.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/utils/aryn_config.py
- lib/sycamore/sycamore/utils/time_trace.py
- lib/sycamore/sycamore/writer.py
- notebooks/SycamorePartitionerExample.ipynb
* Log the incremental output from the server
* Handle errors that happen partway through processing
* Move ray logging setup into default sycamore init
* for testing, add a sycamore.shutdown() to clean up sycamore.init()
* Add support for not loading the model when we're only going to call the server
* Add assertions to code to check for user error
* Switch partitioner to using logger. instead of logging. It's better style, it turned out to
not be necessary.
* Remove caching from aryn_config. It caused problems when called with different parameters
If we're going to re-introduce this we can use @cache which will respect parameters.
* Make SycamorePartitionerExample notebook runnable. The example failed because of missing
files/directories.
> Get logging working in ray

- .github/workflows/testing.yml
This should provide roughly the same coverage, but be significantly cheaper and faster to execute. We run with Python 3.9, the minimum python version we support, to catch cases where we have inadvertently added dependencies on features added in later versions.
> Run Sycamore integ tests only on Python 3.9.

- lib/sycamore/sycamore/llms/openai.py
This PR adds support for an environment variable, `SYCAMORE_HELICONE_API_KEY`, which, when set, will cause the OpenAI client to use Helicone (https://helicone.ai) to issue LLM calls. This allows for greater visibility and debugging, and things like cost tracking etc. It is completely optional.
To use this, one must set up a Helicone account, and get a Helicone API key, and set the env var to this value.
> Add Helicone support.

- lib/sycamore/sycamore/tests/unit/transforms/test_aryn_partitioner.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
The default requests code can be quadratic in the data size if it finds a single long line without a newline because it is doing the standard append to a string trick.  Switch over to chunking based on raw data and explicitly handle splitting by lines for the early status output.
> Fix long line issue in partitioner client

- lib/aryn-sdk/aryn_sdk/partition/partition.py
- lib/aryn-sdk/aryn_sdk/test/resources/json/3m_output.json
- lib/aryn-sdk/aryn_sdk/test/resources/json/3m_output_ocr.json
- lib/aryn-sdk/aryn_sdk/test/resources/json/3m_output_ocr_table.json
- lib/aryn-sdk/aryn_sdk/test/resources/json/3m_output_table.json
- lib/aryn-sdk/aryn_sdk/test/resources/json/SPsort_output.json
- lib/aryn-sdk/aryn_sdk/test/resources/json/SPsort_output_images_page0.json
- lib/aryn-sdk/aryn_sdk/test/resources/json/SPsort_output_images_page1.json
- lib/aryn-sdk/aryn_sdk/test/test_partition.py
requests iter_lines() does n^2 string building which is bad when you have very big lines (such as with extract_images=True). This (I'm like 99% sure) turns that linear.
fyi
```python
byteses = b"hello\nworld\n"
byteses.split(b'\n') # -> [b'hello', b'world', b'']
```
Also updated the test cases since we changed how APS sorts elements. While I was at it, I pretty-printed the json files to simplify the mocking code
adapted from #589
> aryn-sdk iter over content not lines

- lib/sycamore/sycamore/llms/openai.py
Send `user` parameter in OpenAI call based on environment variable `SYCAMORE_HELICONE_USER`
> Support user tracking for Helicone

- .github/workflows/testing.yml
Forgot to update this in https://github.com/aryn-ai/sycamore/pull/599
> Add user id variable to env (Helicone tracking for CI runs)

- lib/sycamore/sycamore/__init__.py
- lib/sycamore/sycamore/connectors/file/materialized_scan.py
- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/data/table.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/executor.py
- lib/sycamore/sycamore/lineage.py
- lib/sycamore/sycamore/plan_nodes.py
- lib/sycamore/sycamore/tests/integration/test_image_utils.py
- lib/sycamore/sycamore/tests/unit/connectors/common/test_base_writer.py
- lib/sycamore/sycamore/tests/unit/test_lineage.py
- lib/sycamore/sycamore/transforms/base.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
Speeds up the new test_lineage.py from ~20s -> ~4s.  Specified via the context. Currently only works for linear pipelines with a source of in-memory documents.  Implementation is the obvious recursive execution.
Attempted further improvements of making import sycamore faster, but it turned out to be very complex.  We have lots of dependencies; started making some of them optional and using conditional imports to keep typechecking working.
Fix a handful of additional type issues beyond the ones the change introduced.
Fix bug in auto-metadata where we calculate lineage without input/output documents.
Have to have the local mode return an Iterator[Document] keeping the Dataset api requires importing ray which takes >0.5s.
Added almost no-op materialize class and docset operator.
> Add local (no-ray) execution mode to speed up lineage development

- lib/sycamore/sycamore/data/table.py
- lib/sycamore/sycamore/tests/unit/data/test_table.py
when you get a table with extra stuff in the tag, e.g. from pubtabnet
```
<html> <head> <meta charset="utf-8"/> <style> table, th, td { border: 1px solid black; font-size: 10px; } </style> </head> <body> <table frame="hsides" rules="groups" width="100%"> <thead> <tr> <td> <b> Kinetic parameter </b> </td> <td> <b> ND </b> </td> <td>...
```
and you try to parse the table string part don't vomit because the string doesn't start with `<table>`
> parse html tables better

- lib/aryn-sdk/aryn_sdk/partition/partition.py
Allows `LimitExceededError` to have a message that makes more sense
> Change Aryn-SDK Error Message

- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/unit/transforms/test_graph_extractor.py
- lib/sycamore/sycamore/transforms/extract_graph.py
Added ```generate_future()``` to the openai client that can be used to request a large amount of openai calls in parallel.
Example usage:
```python
async def gather_api_calls():
tasks = [self.llm.generate_future(prompt_kwargs={"prompt": prompt}, llm_kwargs={...}) for prompt in prompts]
res = await asyncio.gather(*tasks)
return res
res = asyncio.run(gather_api_calls())
```
> Added OpenAI Async client

- lib/sycamore/sycamore/data/table.py
- lib/sycamore/sycamore/tests/unit/data/test_table.py
old algorithm:
for each cell, if I am a rowspan, check all the other cells and bump everything below and to the right of me.
new algorithm:
for each cell, if I need to be bumped, bump myself, and if I'm a rowspan tell the rows below me that there might need to be bumping.
old algorithm failed on a table like
```
__________
|__|  |__|
|  |  |__|
|__|__|__|
```
because the cell on the bottom right was initially in col=0, and the middle cell wouldn't bump it
> fix table html parsing edge case

- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/execution/sycamore_executor.py
- lib/sycamore/sycamore/query/execution/sycamore_operator.py
- lib/sycamore/sycamore/tests/integration/query/execution/test_sycamore_query.py
Allows you to run sycamore queries through generated code. This will become the default once we've tested existing workloads. 
We might also want to have the codegen mode return the result + generated code in 1 call, can think about it as we migrate
> Code executor

- lib/sycamore/sycamore/connectors/file/file_writer.py
- lib/sycamore/sycamore/tests/unit/test_writer.py
Based on customer feedback. This changes the default and fixes the implementation of the makedirs parameter so that the writer will create the directory to write to by default.
> Change the file writer to create the output directory.

- lib/aryn-sdk/aryn_sdk/partition/partition.py
- lib/aryn-sdk/pyproject.toml
adds a param to turn off ssl cert verification (for databricks users where ssl has inconsistencies)
> Add ssl_verify param to aryn-sdk

- .github/workflows/testing.yml
This moves the integ tests to a larger instance.
> Update Github integ test runner.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
This moves the loading of the DETR out of the ArynPDFPartitioner constructor so that we don't load it when using the remote partitioner
> Defer model initialization.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
`response_json = response_json.get("elements")` returns None by default, so this would crash when `response_json` is subsequently iterated. Changing the default to an empty list prevents this error.
> Fixed a problem in detr_partitioner.py

- lib/sycamore/sycamore/connectors/file/file_writer_ray.py
_FileDataSink would crash if you passed it an empty string as `_root` because PyArrow can't create a directory at ""
Now if `_root` is an empty string, it automatically switches to "./" before creating the directory.
> Fixed an error in file_writer_ray.py

- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
We have seen at least one case where table transformers will produce a cell that spans a non-contiguous span of rows (e.g. [8,9,11,12]). This is clearly wrong, and we were asserting on it, but it is quite difficult to update the table transformer heuristics in a way that prevents this without having other potentially deleterious effects on quality. This change simply replaces the row and column spans with list(range(min, max)), which always produces a continuous run of rows/cols.
> Fill in "gaps" in non-contiguous rows and columns from TATR .

- lib/sycamore/pyproject.toml
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/unit/transforms/test_graph_extractor.py
- lib/sycamore/sycamore/tests/unit/utils/test_pydantic_pickling.py
- lib/sycamore/sycamore/transforms/extract_graph.py
- lib/sycamore/sycamore/utils/pickle_pydantic.py
This PR implements using pydantic models as entity schemas to be extracted from text.
**lib/sycamore/pyproject.toml**
- Added pydantic as a dependency
**lib/sycamore/sycamore/docset.py**
- Moved resolving duplicate entities to after all extractors run
**lib/sycamore/sycamore/llms/openai.py**
- Added functionality to use openai structured outputs
- Automatically select the beta client if the response format uses structured outputs
**lib/sycamore/sycamore/tests/unit/transforms/test_graph_extractor.py**
- Change tests to use normal docset inputs instead of hierarchical documents
- Changed entity extractor test to test using pydantic models
**lib/sycamore/sycamore/transforms/extract_graph.py**
- Removed resolve method and made it an importable function to be called after all graph extractors …
> Updated Entity Extractor + Infrastructure Changes

- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
This was causing an assertion failure when the DETR model found a table but table transformers didn't.
We still leave the assertion in for the case where the table transformer model finds more than one table. It is not clear if this is happening in practice, and the fix is more involved, so we defer it.
> Return an empty table when table transformers don't find a table.

- lib/sycamore/sycamore/llms/guidance.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/manual/test_fast_sycamore_import.py
- lib/sycamore/sycamore/transforms/bbox_merge.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
- lib/sycamore/sycamore/writer.py
2.6s to run test before, 1.35 after.
Also include timing of just the import statement, although time after exit seems proportional to the time to import.
> More dependencies at runtime. ~2x speedup on import sycamore test

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/unit/test_writer.py
- lib/sycamore/sycamore/writer.py
before a bunch of the writers were forcing execution by going to the ray level, which would skip the finalize call that materialize needs in order to function. This moves as many of the writers as possible to use DocSet.execute() and for those where it's non-trivial just sticks a finalize in the method after the ray-based execution-forcer
> make sure writers finalize

- lib/sycamore/sycamore/llms/openai.py
Allows us the flexibility to ensure the issue [here](https://github.com/guidance-ai/guidance/issues/506) doesn't show up, which comes up when running notebooks locally. By default set to `False`.
> Add Echo Guidance Flag to suppress IPython HTML Outputs 

- lib/sycamore/sycamore/connectors/neo4j/neo4j_writer.py
- lib/sycamore/sycamore/data/document.py
**neo4j_writer.py**
- Fixed bug where relationship properties were not being added into neo4j(issue with prompt + logic in `_parse_docs`)
- Added support for lists + dictionaries are neo4j properties. Previously, they were flattened but this turns out to not be useful to the end user whilst just doing a `json.dumps()` on them allows them to be used by the user in neo4j with some commands.
**document.py**
- Now checks for text_representation in `self.data.get('text_representation')` before setting it to `self.data.get('table').to_csv()`
> Fixed neo4j relationship property loading + added support for loading lists and dictionaries as properties

- lib/sycamore/sycamore/query/schema.py
- lib/sycamore/sycamore/tests/unit/query/test_schema.py
Current schema extractor breaks with lists which are common
> Handle non-hashable data types in opensearch schema extractor

- lib/sycamore/sycamore/tests/unit/utils/test_fileformat_tools.py
- lib/sycamore/sycamore/utils/fileformat_tools.py
libreoffice runs 1 instance per user, so if multiple tasks try to call this function only 1 succeeds. This is a workaround to force libreoffice to use a different user dir per execution. It probably adds a slight overhead in a single run but supports scaling
> Support concurrent libreoffice executions, fix bug to support s3 source paths in file_format_tools

- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
The table transformer post-processing code had some code (in nms_supercells) that attempted to remove overlapping spanning cells, but it didn't actually prevent a single cell from being put in multiple spanning cells. This could create strange issues with two cells occupying the same space, which screws up html rendering, among other things.
This change assigns each cell to at most one spanning cell. If it intersects multiple spanning cells, we pick the one with the largest intersection.
> Enforce the constraint that each cell is only in one spanning cell.

- lib/sycamore/sycamore/query/execution/sycamore_operator.py
Since the Sycamore Query executor uses `.materialize()`, it is not necessary to separately write traces.
> Remove unnecessary tracing code.

- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/execution/operations.py
- lib/sycamore/sycamore/query/execution/sycamore_executor.py
- lib/sycamore/sycamore/query/execution/sycamore_operator.py
- lib/sycamore/sycamore/reader.py
- lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_executor.py
- lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_operator.py
- lib/sycamore/sycamore/tests/unit/test_context.py
Allow custom context object in query_client.run_plan/query(..). This allows you to pass in your own objects for query execution (e.g. custom llm).
```python
context = sycamore.init(params={OperationTypes.BINARY_CLASSIFIER: {"llm": MyFancyLLM()}})
query_client.query("How many dogs are cats?", index="catdog", context=context)
...
```
Also includes a few more fixes/updates in the lib.
> Default llm in transforms

- lib/sycamore/sycamore/__init__.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/materialize.py
- lib/sycamore/sycamore/materialize_config.py
- lib/sycamore/sycamore/tests/unit/test_materialize.py
During discussion of the blog post, two things came up:
1. changing the constants used to define the source mode
2. adding clear_materialize() so people don't have to delete the source directories to easily force recomputation.
> Improve materialize

- lib/sycamore/sycamore/utils/image_utils.py
Colab reports a different IPython shell than Jupyter, and this was throwing off our image drawing code. I don't love checking for colab explicitly, but there doesn't seem to be an easy way to check that the display method is available otherwise.
> Fix show_pages in Google Colab.

- lib/sycamore/README.md
- lib/sycamore/pyproject.toml
Adds a hard link to the underlying readme and ensures that the `pyproject.toml` file refers to the monorepo README
> Fix Lib/Sycamore README

- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/unit/test_context.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
A few fixes and improvements in @contextvars. This fixes top_k with LLMs being broken currently
1. Bugfix to handle popping keys that don't exist in new kwargs
2. Handle cases where a function might not accept **kwargs and we try to send extra args. In this case we only want to send args that the signature allows
3. Updated top_k and llm_cluster tests to use LLMs from the context
4. Added a bunch of comments in the @contextvars implementation to explain what's going on
> Bugfixes for context_vars

- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_pdf_to_opensearch.py
- lib/sycamore/sycamore/tests/unit/test_context.py
- lib/sycamore/sycamore/tests/unit/transforms/test_entity_extraction.py
`func.__code__.co_varnames[: func.__code__.co_argcount]` doesn't run reliably to inspect a function (as exposed by extract_entity because it's double decorated). Changed to use the inspect lib.
> Fix function signature reading in contextvars

- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/planner.py
- lib/sycamore/sycamore/tests/unit/query/test_planner.py
This PR adds a flag to the SycamoreQueryClient requesting a natural language response. This allows apps to request either natural language or raw data, based on what they need.
> Add natural language result flag.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/partition.py
Sets the default to "auto" when using the remote partitioner and 0.35 when running locally. Also updates all of the type signatures so that type checking passes.
> Update default threshold values for ArynPartitioner.

- lib/aryn-sdk/aryn_sdk/partition/partition.py
The aryn_sdk already does the right thing in terms of what we are sending the service, but the type annotations were not compatible with specifying "auto". This just updates those annotations.
> Update type signatures for threshold in aryn_sdk.

- apps/query-demo/querydemo/Query_Demo.py
This PR makes a couple of tweaks to the Luna demo:
* Markdown links are rewritten to <Preview> elements when supported by the link target.
* Avoid using fancy query operations when doing RAG-only queries.
> A few Luna demo tweaks.

- lib/sycamore/sycamore/connectors/opensearch/utils.py
- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/execution/sycamore_executor.py
- lib/sycamore/sycamore/query/execution/sycamore_operator.py
- lib/sycamore/sycamore/query/operators/llm_filter.py
- lib/sycamore/sycamore/query/operators/query_database.py
- lib/sycamore/sycamore/query/planner.py
- lib/sycamore/sycamore/tests/integration/query/execution/test_sycamore_query.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
- lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_operator.py
- lib/sycamore/sycamore/tests/unit/test_context.py
1. Some bug fixes regarding default vars in context_params
2. Integ test fix for SycamoreQuery missing `natural_language_response=True`
3. Added QueryVectorDatabase operator
Will continue prompt tuning as we play with it. Will also want to port this as a native DocSetReader function at some point.
> Add QueryVectorDatabase to SycamoreQuery

- .github/workflows/draft_release.yml
- lib/sycamore/pyproject.toml
A previous change attempted to avoid our README files getting out of sync by referencing the README at the root of the repo using a relative path in the library pyproject.toml. This unfortunately breaks poetry build. This commit switches back to using the README in the lib directory, and adds a github action step to copy the README during the release process to hopefully avoid drift that way.
> Reverts README change to restore poetry build.

- apps/query-demo/querydemo/Query_Demo.py
When the DocSet returned by the Sycamore query is empty, the resulting string representation is empty, which leads the LLM to hallucinate in interesting ways. This avoids that problem.
> Fix issue with empty tool response leading to hallucinations.

- apps/query-ui/poetry.lock
- lib/sycamore/sycamore/transforms/extract_entity.py
OpenAIEntityExtractor was internally modifying its prompt, causing it to send multiple user messages to the LLM, depending on how it was invoked. This PR fixes this by avoiding modification of the `self._prompt` field.
> Fix bug where prompt is modified by OpenAIEntityExtractor.

- apps/query-demo/querydemo/Query_Demo.py
- apps/query-demo/querydemo/util.py
- apps/query-ui/poetry.lock
- apps/query-ui/queryui/util.py
- lib/sycamore/sycamore/transforms/extract_entity.py
This PR implements a query trace viewer for the Luna demo, which shows the top-level documents emitted from each stage of the query plan. I intend to improve this over time but wanted to get the first version out there.
I've also moved the PDF previews into a dialog so they don't clutter the conversation view.
> Query trace viewer for Luna demo, and better PDF previews.

- examples/html_ingest.py
- examples/ndd_debug.py
- lib/sycamore/sycamore/__init__.py
- lib/sycamore/sycamore/connectors/file/file_scan.py
- lib/sycamore/sycamore/connectors/file/file_writer.py
- lib/sycamore/sycamore/materialize.py
- lib/sycamore/sycamore/tests/integration/connectors/file/test_file_writer.py
- lib/sycamore/sycamore/tests/integration/connectors/file/test_file_writer_to_s3.py
- lib/sycamore/sycamore/tests/unit/connectors/file/test_file_writer.py
- lib/sycamore/sycamore/utils/pyarrow.py
- lib/sycamore/sycamore/writer.py
- notebooks/default-prep-script.ipynb
Working for a few unit tests (file writer), examples (html_ingest, ndd_debug), and notebooks (default-prep-script).
* Update the file writers to work in local mode
* Refactor the code for the database writers to remove duplicate lines.
* Refactor infer_fs so we can use it in multiple places and a variant that will cross check that the user specified fs and the inferred one are the same, in which case we use the inferred path to be more similar to ray.
* Add constants for exec mode to sycamore namespace. Remove materialize constants from default imports.
* Add materialize in a bunch of places to speed up execution.
* Discover we have a strong ray dependency for specifing parallelism. Add TODO to fix this problem.
> Get local mode working 1/n

- apps/query-demo/querydemo/Query_Demo.py
- apps/query-demo/querydemo/util.py
This PR updates the query trace view code to be much more selective about how much data from the traces it retains in memory, and how much it throws at streamlit to render. It also ensures consistency in terms of the column ordering.
This fixes problems with, e.g., TopK queries crashing Streamlit due to OOM.
> Fix query trace viewer.

- lib/sycamore/sycamore/transforms/standardizer.py
This makes the error message less confusing if the value of the date time property to be standardized happens to be None.
> Fix error message on None value passed to DateTimeStandardizer.

- .github/workflows/testing.yml
- apps/jupyter/bind_dir/setup.sh
- apps/query-ui/external_ray_wrapper.py
- apps/query-ui/queryui/configuration.py
- apps/query-ui/queryui/custom_client.py.sample
- apps/query-ui/queryui/test_configuration.py
- examples/query/simple_ntsb.py
- lib/sycamore/sycamore/query/client.py
setup.sh: Remove the , that was added. We need the , to get multiple simultaneous installs in a single bunch, and need to remove it for the script.
.force_directory_creation: Empty file to make sure the cache_dir exists to allow running the container
configuration.py: Change the way we hook a custom client into the query ui -- the existing approach
was fragile. If the API for specifying the custom client changes, we want people to get a git
conflict when they try to merge because they probably have to adjust how they configure the
client. By always running the code we can be sure that it parses, it was very easy to have a bug
in parsing cause it to not work. For example, the sample file had the wrong function name. Remove
some parameters that are not useful, a custom client can't take an …
> Sundry improvements while using luna in a customer.

- apps/query-demo/querydemo/Query_Demo.py
- apps/query-demo/querydemo/util.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/planner.py
This PR makes it possible for a Luna app to provide its own few-shot examples for query plan generation, based on the
specific knowledge of the data and types of queries likely to be issued.
It also fixes a small bug in docset.llm_cluster_entity where a doc that does not have the field used to perform clustering would cause this operation to crash.
> Some improvements to query plans for Luna demo.

- apps/query-ui/queryui/Sycamore_Query.py
- lib/sycamore/sycamore/connectors/opensearch/opensearch_writer.py
- lib/sycamore/sycamore/query/operators/query_database.py
- lib/sycamore/sycamore/query/planner.py
This PR fixes an issue where Luna would issue an OpenSearch query using the `match` operator against the `properties.path` field, which does not do the right thing in most cases. This change has it use the `.keyword` version
of this field instead, with a wildcard match.
This pattern should probably generalize to other kinds of fields where a keyword match is more appropriate, but there
needs to be more thought into how that would be done.
> Have Luna use .keyword field for path field.

- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/schema.py
- lib/sycamore/sycamore/tests/unit/query/test_schema.py
- lib/sycamore/sycamore/tests/unit/utils/test_nested.py
- lib/sycamore/sycamore/utils/nested.py
* Include all properties instead of the ones just under properties.entity Keys are named with the full path, so it's easy to tell which properties are entity properties.
* Handle properties with varying types, for int/float it takes the most general type. For other cases it takes the first and logs a message since there are likely to be problems.
> Improve luna property handling

- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/connectors/pinecone/pinecone_reader.py
- lib/sycamore/sycamore/connectors/weaviate/weaviate_reader.py
- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/reader.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_opensearch_read.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
Adds a reconstruct_document flag to the opensearch reader. This allows you to query an opensearch index and receive a DocSet in it's pre-exploded form. This is useful to do original document level transforms on a DocSet.
Added a "_doc_source" property to be able to identify which elements were loaded as query hits, and which were loaded as part of document reconstruction.
Eventually we might want to move this as a separate transform but this gives us some immediate value and can be moved out later.
> add read.opensearch(reconstruct_document =True) option

- .gitignore
- examples/bench.py
- lib/sycamore/sycamore/connectors/base_reader.py
- lib/sycamore/sycamore/connectors/base_writer.py
- lib/sycamore/sycamore/connectors/file/file_scan.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/executor.py
- lib/sycamore/sycamore/plan_nodes.py
- lib/sycamore/sycamore/tests/integration/transforms/test_map.py
- lib/sycamore/sycamore/tests/unit/connectors/common/test_base_writer.py
- lib/sycamore/sycamore/tests/unit/transforms/test_base.py
- lib/sycamore/sycamore/tests/unit/transforms/test_mapping.py
- lib/sycamore/sycamore/tests/unit/transforms/test_sketcher.py
- lib/sycamore/sycamore/tests/unit/utils/test_ray_utils.py
- lib/sycamore/sycamore/transforms/base.py
- lib/sycamore/sycamore/transforms/embed.py
- lib/sycamore/sycamore/transforms/extract_schema.py
- lib/sycamore/sycamore/transforms/map.py
- lib/sycamore/sycamore/transforms/partition.py
- lib/sycamore/sycamore/transforms/sketcher.py
- lib/sycamore/sycamore/writer.py
- notebooks/default-prep-script.ipynb
- notebooks/elasticsearch-writer.ipynb
- notebooks/subtask-sample.ipynb
* Allows us to remove a dependency on importing ray.
* tests/integration/test_map.py confirms that the parallelism setting is working
* notebooks/default-prep-script.ipynb verifies we don't import ray in local mode
* moved serializability checks into the ray execution function. For the writer, I could just remove the serializeability check since it's done by basemap (manually verified)
* add check_serializable test as an example of something that can't be serialized.
* a fair bit of ugly code to patch in ray stuff in cases where we bypass the Executor in tests.
* fix handling of parallelism in file readers, they use -1 == unlimited, but ActorPoolStrategy asserts on size <= 0
> Define parallelism on nodes

- examples/markdown.py
- examples/s3_ingest.py
- lib/sycamore/sycamore/connectors/file/file_scan.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/executor.py
- lib/sycamore/sycamore/transforms/regex_replace.py
* Switch examples/markdown.py and examples/s3_ingest.py over to local mode.
* Fix s3_ingest to have the correct path adjustment. Fix it to only setup the filesystem if the AWS env vars are not present (enabled verifying that auto-fs detection worked) Switch it from taking a manifest to taking a path. I was unable to find an example of using the manifest in files, and given the python path bug, it means no one was using the script.
* Fix file scan to be able to work when the filesystem isn't specified.
* Add logging for when we run steps in local mode -- it was hard to debug if things were having problems or just being slow.
* docset.py, regex_replace.py: Fix escape sequences in docstrings that get warnings on 3.12.
> Get Local Mode working 2/n

- lib/sycamore/sycamore/connectors/base_reader.py
- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_html_to_opensearch.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_opensearch_read.py
- lib/sycamore/sycamore/tests/integration/transforms/test_rerank.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
- lib/sycamore/sycamore/tests/unit/transforms/test_similarity.py
- lib/sycamore/sycamore/transforms/__init__.py
- lib/sycamore/sycamore/transforms/map.py
- lib/sycamore/sycamore/transforms/similarity.py
Allows you to do:
```python
similarity_scorer = HuggingFaceTransformersSimilarityScorer(ignore_doc_structure=True)
doc_set = context.read.binary(paths).rerank(
similarity_scorer=similarity_scorer, query="is this a cat?", score_property_name=score_property_name, limit=5
)
result = doc_set.take()
```
A key callout here is if we're doing a rerank on a non-exploded DocSet (i.e. not rag on chunks style), we will order Documents by their highest matching chunk, even though another Document might have slightly lower scoring but more chunks that are similar.
This PR also adds a local mode for BaseDBReader, will update our integration tests touching DBs to test both local and ray modes.
> Add similarity scoring and rerank transform

- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/functions/document.py
- lib/sycamore/sycamore/tests/conftest.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_html_to_opensearch.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_opensearch_read.py
- lib/sycamore/sycamore/tests/integration/transforms/test_partition.py
- lib/sycamore/sycamore/tests/unit/transforms/test_aryn_partitioner.py
- lib/sycamore/sycamore/tests/unit/transforms/test_partition.py
- lib/sycamore/sycamore/tests/unit/transforms/test_similarity.py
- lib/sycamore/sycamore/tests/unit/utils/test_bbox_sort.py
- lib/sycamore/sycamore/transforms/bbox_merge.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/extract_document_structure.py
- lib/sycamore/sycamore/transforms/extract_table.py
- lib/sycamore/sycamore/transforms/mark_misc.py
- lib/sycamore/sycamore/transforms/markdown.py
- lib/sycamore/sycamore/transforms/merge_elements.py
- lib/sycamore/sycamore/transforms/partition.py
- lib/sycamore/sycamore/transforms/similarity.py
- lib/sycamore/sycamore/transforms/sketcher.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/utils/bbox_sort.py
- lib/sycamore/sycamore/utils/html_utils.py
- lib/sycamore/sycamore/utils/image_utils.py
1. Add a seq_no attribute to Element, this is meant to represent the order of elements resulting from a partitioner. The partitioner is still responsible for what that ordering means.
2. Add local and ray exec_mode tests for DB readers (via opensearch tests)
3. Lots of mypy fixes and "page_number" constant fixes
> Element ordering and test improvements

- lib/sycamore/sycamore/tests/integration/transforms/test_rerank.py
- lib/sycamore/sycamore/tests/unit/transforms/test_sort.py
- lib/sycamore/sycamore/transforms/basics.py
- lib/sycamore/sycamore/transforms/sort.py
Fix an integ test I broke in https://github.com/aryn-ai/sycamore/commit/0a3ad992a471d68658d0bebc9d50b73b599d092f
Add local mode for limit and sort
> Test fixes and more local mode

- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/integration/connectors/opensearch/test_opensearch_read.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
**1. Support document model in llm_filter and some performance improvements**
llm_filter will work on a DocSet made of original Documents (i.e. pre-exploded state) when using `use_elements=True`
* Element iteration "early stopping" - a record (document) passes the filter if any of the document's elements pass the llm_filter condition, we don't evaluate every element. This helps for documents which would be a hit, but doesn't for documents which would not (because we would still iterate over every element)
* Optionally, it sorts elements by a similarity score to get potential llm hits sooner
* `keep_none` flag to dictate behavior for a missing property value
None of these are perfect but they align with the use cases we have so far and can keep iterating.
**2. Sorted elements returned by …
> Get llm_filter to support document structure + similarity sorting for elements

- docs/source/sycamore/connectors/pinecone.md
Moves the configuration for Pinecone piece to the bottom of the docs since it is not needed to connect to it from Sycamore.
> Adjust Pinecene Docs for Clarity

- lib/sycamore/sycamore/connectors/weaviate/weaviate_writer.py
asdict recurses into inner dataclasses, and ApiKey is a dataclass, so inside the weaviate client library it would see {"api_key": ";kaerjgnejrgheskrgjvnd"} and go "that's not an ApiKey!" and crash
> fix bug in weaviate writer causing api keys to be of wrong type

- lib/sycamore/sycamore/transforms/text_extraction/ocr_models.py
Allow custom args for easyocr
```python
with Image.open(TEST_DIR / "resources/data/imgs/sample-detr-image.png") as image:
e = EasyOcr(model_storage_directory="/Users/vinayakthapliyal/.EasyOCR/model/", download_enabled=False)
print(e.get_text(image))
```
> Expose local easyocr kwargs

- lib/sycamore/sycamore/tests/unit/transforms/test_detr_partitioner.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
Let's you pass in a configured object, the current implementation would allow you to configure the model
Tested with test
> Allow passing custom ocr object to arynpartitioner

- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/reader.py
- lib/sycamore/sycamore/tests/integration/query/test_query_opensearch.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
- lib/sycamore/sycamore/tests/unit/transforms/test_detr_partitioner.py
When using `@context_params`, all kwargs specificied in the global Context would get passed into the reader.opensearch method. Those were being forwarded into the opensearchpy client. Changed the parameter to explicitly accept query_kwargs. I don't quiet know why we have kwargs anyway but don't want to mess with that
> Opensearch kwargs fix

- lib/sycamore/sycamore/connectors/file/file_scan.py
- lib/sycamore/sycamore/reader.py
- notebooks/metadata-extraction.ipynb
* Use materialize to save the work of re-partitioning which is >50% of notebook runtime.
* Use materialize to avoid re-computation from show/take/write
* Fix readers to use the override_num_blocks parameter instead of parallelism; that's the recommended parameter from ray, and using parallelism created confusion with the parallelism setting for ray execution
* Remove parallelism setting from the notebook. It was causing hangs.
> Make metadata-extraction.ipynb work

- lib/sycamore/sycamore/connectors/duckdb/duckdb_reader.py
- lib/sycamore/sycamore/connectors/duckdb/duckdb_writer.py
Replaces `embeddings` with `embedding` and ensures we always get iterables from the DuckDB reader.
> Fix DuckDB Spelling Error

- lib/sycamore/sycamore/data/document.py
- lib/sycamore/sycamore/tests/unit/transforms/test_similarity.py
- lib/sycamore/sycamore/transforms/similarity.py
1. **Allow missing element_id in similarity score source for backwards compatibility**
Data loaded in opensearch prior to https://github.com/aryn-ai/sycamore/commit/0a3ad992a471d68658d0bebc9d50b73b599d092f fails in similarity scoring because of missing element_id. 
I'm choosing to explicitly handle the missing value here rather than defaulting when loading from the index to prevent unintended behavior.
2. **Un-enum DocumentSource because it causes json serialization problems**
To serialize a Document object we'd need to use a custom json encoder because of this which is overkill for what is essential a class of constant strings
> Bugfixes: DocumentSource enum serialization and missing element_id in old data

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/query/execution/sycamore_executor.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
kwargs were being populated by @context_params but unused in the function. They were being passed as is to the underlying ray dataset execution which would complain about unknown additional args. Removed kwargs since it isn't needed here. This was breaking on a vector search query plan but undetected because the integ tests are broken.
Fixed result node naming in sycamore query codegen. Undetected because integ tests broken
> Bug fixes: remove kwargs in docset.rerank, sycamore query codegen

- lib/sycamore/sycamore/data/__init__.py
- lib/sycamore/sycamore/transforms/llm_query.py
- lib/sycamore/sycamore/transforms/merge_elements.py
The ``Table merger`` handles 3 operations
1. If a text element (Caption, Section-header, Text...) contains the regex pattern anywhere in a page
it is attached to the text_representation of the table on the page.
2. LLMQuery is used for adding a table_continuation property to table elements. If the table is
a continuation from a previous table the property is stored as true, else false.
3. After LLMQuery, table elements which are continuations are merged as one element.
> Add Table Merger

- lib/sycamore/sycamore/llms/__init__.py
- lib/sycamore/sycamore/llms/bedrock.py
- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/llms/test_bedrock.py
- lib/sycamore/sycamore/tests/integration/llms/test_openai.py
- lib/sycamore/sycamore/tests/unit/llms/test_bedrock.py
This is a crude but serviceable LLM client that uses Bedrock. I have currently tested it only with Sonnet 3.5 and different models may have different requirements and parameters, but we can add those over time as needed.
Since there are so many different models with somewhat different formats, it's a little hard to test them all.
I lifted the cache logic into the `LLM` base class so it is reusable across subclasses, although the OpenAI variant needs to account for the response type in the cache key.
> Basic Bedrock LLM client.

- lib/aryn-sdk/aryn_sdk/partition/art.py
We sometimes have missing tables and empty bboxes, this ensures the drawing code does not break over that.
> Handle Drawing Missing Tables and Cells

- lib/sycamore/sycamore/transforms/detr_partitioner.py
Previously cropping to bounding box had no padding, the `crop_to_bbox` function has a default padding of 10 (done since the DETR model often chops very small) which might have caused issues in the table merging code.
> Crop To Bbox Error

- lib/sycamore/sycamore/tests/integration/transforms/test_embed.py
- lib/sycamore/sycamore/transforms/embed.py
OpenAI doesn't like it if you try to embed the empty string, but it gives a terrible error message
```
BadRequestError: Error code: 400 - {'error': {'message': "'$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```
Anyway, don't do that. (also pure whitespace seems to be a problem)
> don't embed the empty string with openai

- lib/sycamore/sycamore/llms/bedrock.py
- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/transforms/test_summarize_images.py
- lib/sycamore/sycamore/transforms/summarize_images.py
- lib/sycamore/sycamore/utils/image_utils.py
This commit adds a generic LLMImageSummarizer that takes an LLM instance. In order to account for differences in image formats accepted by the LLMs, I also added a `format_image` method to the LLM interface. Finally, I fixed a serialization issue in the Bedrock class by not serializing the boto client.
> Support SummarizeImages with non-OpenAI LLMs.

- apps/query-eval/data/ntsb-mini.yaml
- apps/query-eval/queryeval/driver.py
- apps/query-eval/queryeval/main.py
- apps/query-eval/queryeval/types.py
This adds support for two new fields in the query type:
* `tags` - A list of tags associated with the query, which can be used for filtering
* `notes` - Human-readable and editable notes which we can add (but still parseable as opposed to using comments in the YAML).
This also adds the `notes` field to the result type.
Adds `--tags` option to `main.py` to pass tags to filter by.
> Add support for tags and notes.

- lib/sycamore/sycamore/llms/bedrock.py
- lib/sycamore/sycamore/llms/prompts/default_prompts.py
- lib/sycamore/sycamore/tests/unit/transforms/test_schema.py
- lib/sycamore/sycamore/transforms/extract_schema.py
We previously had OpenAI-specific versions of these, even though they weren't particularly tied to the LLM. This commit generalizes those classes and tweaks the Bedrock llm implementation to handle the basic guidance prompts so that it works with the existing implementation.
> Create LLMSchemaExtractor and LLMPropertyExtractor classes.

- lib/sycamore/sycamore/tests/unit/transforms/test_merge_elements.py
- lib/sycamore/sycamore/transforms/merge_elements.py
there was a code path that would cause new elements to have no "token_count", which would then crash the program
> fix empty strings in section headers

- lib/sycamore/sycamore/tests/unit/utils/test_pdf_utils.py
- lib/sycamore/sycamore/utils/pdf_utils.py
This copies functionality present in the Aryn Partitioning Service for
selecting specific pages or ranges of pages from pdfs. When applied to
a pdf Document, this will both update the binary_representation to
contain a valid pdf of only the selected pages, as well as retain only
the elements pertaining to those pages.
> Select pages

- lib/sycamore/sycamore/materialize.py
- lib/sycamore/sycamore/tests/unit/test_materialize.py
if you specified the advanced path={"root": "s3://soemthing"} it would incorrectly translate the root to a Path which would remove one of the /'s and then the filesystem inference would interpret it as a local file.
> fix materialize bug with s3 filesystem

- lib/remote-processors/remote_processors/server/processor_registry.py
- lib/sycamore/sycamore/materialize.py
- lib/sycamore/sycamore/tests/unit/transforms/test_graph_entity_extractor.py
- lib/sycamore/sycamore/tests/unit/transforms/test_graph_relationship_extractor.py
- lib/sycamore/sycamore/tests/unit/transforms/test_resolve_graph_entities.py
- lib/sycamore/sycamore/tests/unit/utils/test_import_utils.py
- lib/sycamore/sycamore/tests/unit/utils/test_pydantic_pickling.py
- lib/sycamore/sycamore/transforms/extract_graph_entities.py
- lib/sycamore/sycamore/transforms/extract_graph_relationships.py
This PR fixes issues in the code that were leading to a bunch of mypy warnings. We now get no output from mypy when running on this branch (which is good).
It also replaces the test that was using `reveal_type` with the equivalent (and simpler) `assert_type`.
> Fix mypy warnings.

- lib/sycamore/sycamore/transforms/llm_query.py
- lib/sycamore/sycamore/transforms/merge_elements.py
1. I observed the LLM sometimes having issues distinguishing where one table ended and the next started, so I added headers - either ELEMENT 1/ELEMENT 2 or DOCUMENT 1/DOCUMENT 2 in the llm_query transform.
2. Added a default implementation for preprocess_element and postprocess_element in the ElementMerger base class. This just reduces code in some simple sub-classes.
3. Added code to update the table_continuation to be True or False. This is because I ended up getting better results when asking the LLM to explain its reasoning in some cases, but I didn't want all of the output carried along in the element.
4. Minor fix to address an invalid escape character warning in a comment.
> Couple of minor fixes and tweaks to the table merger.

- lib/sycamore/sycamore/connectors/common.py
- lib/sycamore/sycamore/connectors/duckdb/duckdb_writer.py
- lib/sycamore/sycamore/connectors/elasticsearch/elasticsearch_writer.py
- lib/sycamore/sycamore/tests/unit/connectors/duckdb/test_duckdb_reader.py
- lib/sycamore/sycamore/tests/unit/connectors/duckdb/test_duckdb_writer.py
- lib/sycamore/sycamore/tests/unit/connectors/elasticsearch/test_elasticsearch_reader.py
- lib/sycamore/sycamore/tests/unit/connectors/elasticsearch/test_elasticsearch_writer.py
- lib/sycamore/sycamore/tests/unit/connectors/pinecone/test_pinecone_reader.py
- lib/sycamore/sycamore/tests/unit/connectors/pinecone/test_pinecone_writer.py
Adds unit tests for the Pinecone, Elasticsearch, and DuckDB readers and writers, fixes bugs, and refactors DuckDB to not hardcode the schema.
> Add Lots of Connector Unit Tests

- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
This makes it possible to sort the results by score and do a limit.
> Add score to each document in OpenSearch query result.

- lib/sycamore/sycamore/transforms/bbox_merge.py
- lib/sycamore/sycamore/transforms/mark_misc.py
Fixes bug that where `MarkDropHeaderFooter` always adds `_drop` to all elements, causing all elements to be dropped. This is because the parameters for `MarkDropHeaderFooter.__init__` are different from `MarkDropHeaderFootermark_drop_header_footer`:
```python
def __init__(self, child: Node, top: float = 0.05, bottom: Optional[float] = None, **resource_args):
if bottom is None:
bottom = top
lo = top
hi = 1.0 - bottom
super().__init__(child, f=MarkDropHeaderFooter.mark_drop_header_and_footer, args=[lo, hi], **resource_args)
@staticmethod
@timetrace("markHeadFoot")
def mark_drop_header_and_footer(parent: Document, lo: float, hi: float) -> Document:
for elem in parent.elements:
bbox = elem.data.get("bbox")
if (bbox is not None) and ((bbox[1] > hi) or (bbox[3] < lo)):
elem.data["_drop"] = True …
```
> Fix `mark_bbox_preset`'s `MarkDropHeaderFooter` parameter

- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/connectors/opensearch/utils.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
1. Reduce batch size when loading elements to reconstruct docs, by default OpenSearch supports a max of 10k results so this keeps us within that limit without needing to play with the index and cluster
2. Allow get_knn_query to work with min_score knn queries
> OpenSearch improvements

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/partition.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
We currently drop all table outputs that are not matched to tokens, but this is not required since we anyways chop the image after the DETR model. With this we aim to union back in outputs that did not fit into the original table structure, either by matching to existing cells, or creating new rows and columns for them. This is hidden behind a feature flag `table_extractor_options` that by default does not enable this until we are sure of no regressions.
> Union OCR / PDFMiner Tokens with Table Outputs

- lib/sycamore/sycamore/transforms/similarity.py
The tokenized data was living in the CPU (since tokenizer is only on the cpu), needed to move it to the gpu for scoring
> Move tokenized data to device

- lib/sycamore/sycamore/tests/integration/query/execution/test_sycamore_query.py
The default planner would execute a rewrite rule that would prevent QueryVectorDatabase from ever being used in the test question's prompt. Updated the test to get more reliable usage. Obviously, still depends on the llms mood
> Update vectorsearch query test

- lib/sycamore/sycamore/connectors/base_reader.py
- lib/sycamore/sycamore/connectors/base_writer.py
- lib/sycamore/sycamore/connectors/common.py
- lib/sycamore/sycamore/connectors/duckdb/duckdb_reader.py
- lib/sycamore/sycamore/connectors/duckdb/duckdb_writer.py
- lib/sycamore/sycamore/tests/unit/connectors/duckdb/test_duckdb_writer.py
- lib/sycamore/sycamore/writer.py
Client connections often do not close properly when implicitly handled, here we add the ability to explicitly close them and add it for DuckDB, where this problem was first discovered.
> Add Closure of Client Connections for Connectors

- README.md
- apps/query-eval/queryeval/driver.py
- apps/query-eval/queryeval/main.py
- apps/query-eval/queryeval/test_driver.py
- apps/query-eval/queryeval/types.py
- apps/query-server/queryserver/main.py
- lib/sycamore/sycamore/executor.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/result.py
- lib/sycamore/sycamore/tests/unit/query/test_result.py
This PR adds logic to `SycamoreQueryResult` to return the list of Document paths referenced by the query.
The idea here is to provide a "reasonably selective" set of documents that a query is using in generating its final response. To this end we walk the query tree from the result node up and return the set of docs from the first node (or set of nodes) that return docs, rather than those that return non-doc values (like text chunks or singleton values).
This PR also adds the resulting set to the response returned in `query-server`.
I ended up changing how this worked a bit from @baitsguy's previous implementation (in a private repo).
> Return the list of documents referenced in a Luna query.

- lib/sycamore/sycamore/query/strategy.py
Not all LLMs support seed, and we're seeing validation errors from the unsupported LLMs for this. The param should be moved to the LLM implementation if someone wants to use it.
> Remove seed from rewrite prompt

- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/llms/test_openai.py
There was a bug in how we pickled OpenAI class instances specifically with Azure. Azure OpenAI is a bit weird in that the "deployment name" of a model can be different than the normal OpenAI name. This makes it impossible to use the standard models from the OpenAIModels Enum. Instead, we typically created separate OpenAIModel instances. The problem was that when we pickled the OpenAI object, it saved just the model name, and then tried to recreate the model option by using the Enum. This change pickles the entire OpenAIModel class instead of just the name. Also adds a test that demonstrates the bug (and fix). The other tests were passing because they called the OpenAI methods directly and didn't pickle the object. The object will be pickled in basically any Sycamore job using ray.
> Fix OpenAI __reduce__ methods to handle Azure deployment names.

- lib/sycamore/sycamore/query/schema.py
- lib/sycamore/sycamore/tests/unit/query/test_schema.py
This PR fixes issues where the samples retrieved from OpenSearch are mixed in terms of their types. It addresses two cases:
* In cases where there is a mix of singleton and list types, we promote to a list.
* In cases where there is a mix of singleton types (e.g., bools and ints), we promote to string.
> Fix mixed samples for schema extraction.

- lib/sycamore/sycamore/utils/import_utils.py
people see, copy, and paste `pip install sycamore-ai[extra]` in the requires_module error message and then get zsh errors bc they need to quote it.
> Improve suggested install command

- apps/query-eval/queryeval/driver.py
- apps/query-eval/queryeval/test-results.yaml
- apps/query-eval/queryeval/test_driver.py
- apps/query-eval/queryeval/types.py
- apps/query-server/queryserver/main.py
- lib/sycamore/sycamore/query/result.py
- lib/sycamore/sycamore/tests/unit/query/test_result.py
When trying to retrieve docs for a query, we return them in a descending sorted order by a list of properties you can specify. It defaults to using "score" (from opensearch results), and "_rerank_score" (if a rerank operation was run)
> Sort retrieval docs by score properties if they exist

- lib/sycamore/sycamore/query/execution/operations.py
- lib/sycamore/sycamore/tests/unit/query/test_operations.py
Default 120k let's you work with 32k context window models. If we know we're using 128k token models, we should configure this explicitly.
> Add 120k max chars (default) for summarize_data

- apps/query-eval/queryeval/driver.py
- apps/query-eval/queryeval/types.py
When we started returning raw results as part of QueryResult writing to yaml was broken because it could only handle pydantic types. Added some types with simple doc level fields
> Queryeval docset write fix

- lib/aryn-sdk/aryn_sdk/partition/partition.py
Rename `convert_image` to `convert_image_element`.
> Fix `aryn-sdk`'s `convert_image_element` example

- .github/workflows/testing.yml
Blacksmith has been flaky due to memory and cache issues so we revert unit tests since they are blocking.
> Revert Unit Tests to GitHub Actions

- apps/query-eval/data/ntsb-full.yaml
- apps/query-eval/queryeval/driver.py
- apps/query-eval/queryeval/queryeval_types.py
- apps/query-eval/queryeval/test_driver.py
This PR makes some tweaks to the questions and ground truth answers for CIDR-25 evaluation, and fixes a bug in the query-eval tool.
> Updated NTSB queries and ground truth for CIDR-25 paper.

- lib/sycamore/sycamore/query/execution/operations.py
- lib/sycamore/sycamore/tests/unit/query/execution/test_sycamore_executor.py
This should fix the issue where SummarizeData leaves us with an incomplete materialize dir when the total doc size exceeds the LLM token limit.
> Fix SummarizeData so that downstream .materialize operations will work.

- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/operators/query_database.py
- lib/sycamore/sycamore/query/planner.py
- lib/sycamore/sycamore/query/strategy.py
- lib/sycamore/sycamore/tests/unit/query/test_strategy.py
1. Magical prompting and example improvements for:
1 Using vector search when appropriate
2 Use match_phrase for proper nouns
1. Disable vector-search-removal from default strategy
> Query planner improvements

- lib/sycamore/sycamore/tests/unit/transforms/test_embed.py
- lib/sycamore/sycamore/transforms/embed.py
Once the client is intialized, the embedder is no longer serializable. This change simply skips the client when serializing attributes. It is recreated if it is set to None.
> Make OpenAIEmbedder serializable after client has been initialized.

- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
1. Abstract out the structure model initialization so I can easily swap a Deformable DETR in.
2. Add apply_thresholds param to extract to control whether to threshold the objects by score from the model
3. Change behavior when there are multiple table objects to take the one with the highest score rather than whatever's first.
4. Add subclass that uses Deformable DETR.
> Add deformable table extractor

- lib/sycamore/sycamore/data/metadata.py
- lib/sycamore/sycamore/llms/bedrock.py
- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/tests/integration/llms/test_bedrock.py
- lib/sycamore/sycamore/tests/integration/transforms/test_map.py
- lib/sycamore/sycamore/tests/unit/llms/test_bedrock.py
- lib/sycamore/sycamore/tests/unit/transforms/test_mapping.py
- lib/sycamore/sycamore/transforms/base.py
- lib/sycamore/sycamore/utils/thread_local.py
- poetry.lock
- pyproject.toml
* Could also be used to propagate metadata down, e.g. node ids in Luna
* Add devtools to help with debugging
* Extend llm generate to calculate metadata
> Add helper for thread local variables that can be used to add metadata to the output stream

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
Let's you look at a document and figure out what it's llm_filter score was + which element contributed to the highest score
We're probably want some generic version of this citation stuff for transforms that look at a doc's elements, but this is important for debugging right now
> Propagate element level llm_filter output to doc.properties

- lib/sycamore/sycamore/utils/image_utils.py
we got a table with a cell with no bbox. looking into where that came from but for now let's not crash if we can't get a bbox.
```python
doc = "s3://aryn-public/ntsb/FTW95FA129.pdf"
ds = ctx.read.binary(paths = doc, binary_format = "pdf").partition(ArynPartitioner(extract_table_structure=True, extract_images=True))
show_pages(ds)
```
> don't die if box is None in try_draw_boxes

- lib/sycamore/sycamore/tests/unit/transforms/test_table_transfomers.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
Found the codepath where we don't attach a bbox to the table cells
> when there's no table structure, take the token bbox for the cell bbox

- lib/sycamore/sycamore/transforms/split_elements.py
Previously, splitting documents that contained tables after partitioning them without using `extract_table_structure` could cause an exception to be raised when splitting a table element. This fix allows those documents to be split without error.
> Fix `split_elements` for table elements with no `elem.table` attribute

- lib/sycamore/sycamore/connectors/elasticsearch/elasticsearch_writer.py
- lib/sycamore/sycamore/transforms/extract_schema.py
Extract schema would previously return a string with `None` in failure cases which is incompatible with the normal dictionary return type. This was causing issues when writing out to connectors, and is fixed here.
> Fix Extract Schema Empty Return

- lib/sycamore/sycamore/connectors/base_writer.py
Without this, tracking down what went wrong is much harder.
> Add logging of the full exception in base_writer.

- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/tests/unit/data/test_element.py
Ran into a case of custom document processing that resulted in a missing element type.
> Fix create_element to not crash on bad element types

- lib/sycamore/sycamore/transforms/split_elements.py
Also stops logging the element the recursion stopped on. We are increasing the recursion depth of the temporary fix from #1073 so that it is less likely to cause `split_elements` to fail on documents that worked before.
> Increase max recursion depth for `split_element`'s `split_one`

- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
1. For thresholding, if we would eliminate all rows or columns instead set the threshold to the max-confidence one minus epsilon
2. For slot_into_containers, if a package is contained equally in two containers (usually this means that the package is fully contained in both), slot it into the smaller container.
3. Use the biggest "table" class object, rather than the most confident.
> Misc table transformers post-processing

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
- lib/sycamore/sycamore/utils/model_load.py
something something lockfile something something deduplication
> move deformable detr safe loading code

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
- lib/sycamore/sycamore/tests/unit/transforms/test_extract_entity.py
- lib/sycamore/sycamore/tests/unit/transforms/test_llm_filter.py
- lib/sycamore/sycamore/transforms/extract_entity.py
- lib/sycamore/sycamore/transforms/llm_filter.py
- lib/sycamore/sycamore/transforms/similarity.py
- lib/sycamore/sycamore/utils/llm_utils.py
- lib/sycamore/sycamore/utils/similarity.py
1. Added reranking of elements and element merging/chunking for robustness in LLM Extract Entity. (Works only if LLM returns "None" if it doesn't find the entity in the chunk, which is the default in Luna operator prompt)
2. Refactored code to make use of element similarity sorter, mock tokenizer.
3. Minor bug fix: changed element_index to _element_index for adding to content for LLM Filter.
> Add-tokenizer-and-reranking-to-LLM-ExtractEntity

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/llms/prompts/default_prompts.py
- lib/sycamore/sycamore/query/schema.py
- lib/sycamore/sycamore/schema.py
- lib/sycamore/sycamore/tests/integration/transforms/test_data_extraction.py
- lib/sycamore/sycamore/transforms/extract_schema.py
(This is a sequence of PRs)
Introduces a Schema class in sycamore. Allows you to extract properties from that schema in the `extract_properties` transform. Test validates some basic cleanup and formatting in the extracted info
Next big step will be to refactor sycamore.query to work against this object.
> Schema object + entity extraction support

- lib/sycamore/sycamore/transforms/embed.py
1. https://github.com/openai/openai-python/issues/418 We do not need to remove newline characters in OpenAI embeddings.
2. Table structure (in csv form) would benefit the most from this.
> Keep newline in OpenAI Embedder

- lib/sycamore/sycamore/data/element.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/tests/integration/transforms/test_embed.py
- lib/sycamore/sycamore/tests/unit/transforms/test_embed.py
- lib/sycamore/sycamore/transforms/embed.py
1. Allow .embed() transform to operate on element level (without exploding). 
2. Refactor code for Embedder class to handle orchestration of batching.
> Add Embed at Element Level

- apps/query-eval/queryeval/queryeval_types.py
- apps/query-server/queryserver/main.py
- apps/query-ui/queryui/Sycamore_Query.py
- apps/query-ui/queryui/util.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/planner.py
- lib/sycamore/sycamore/query/schema.py
- lib/sycamore/sycamore/tests/integration/query/test_planner.py
Other places are currently passing OpenSearchSchema to the planner (e.g. query-eval, testing scripts) so I need to support both OpenSearchSchema and Schema in the planner right now.
Also had to add an explicit `OpenSearchSchema.to_schema()` method because both objects define a 'fields' attribute of different types :(
> Get sycamore.query to work with Schema instead of only OpenSearchSchema

- lib/sycamore/sycamore/tests/unit/transforms/test_table_extractor.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
Adds a 'hybrid' table extractor that wraps DeformableTableExtractor and TableTransformerExtractor by selecting one to use based on the size of the table element.
> Add hybrid table extractor

- lib/sycamore/sycamore/data/docid.py
- lib/sycamore/sycamore/materialize.py
- lib/sycamore/sycamore/tests/unit/data/test_docid.py
- lib/sycamore/sycamore/tests/unit/test_materialize.py
see #1090 
":" is illegal in windows filesystem
very useful [stackoverflow page](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names)
> fix materialize on windows

- .github/workflows/linting.yml
- .github/workflows/testing.yml
- CONTRIBUTING.md
- docs/source/sycamore/connectors/opensearch.md
- lib/sycamore/sycamore/connectors/opensearch/opensearch_writer.py
- lib/sycamore/sycamore/writer.py
Adds automatic retries to the OpenSearch writer, along with default backoff and retry values. This helps deal with `TransportError` bugs when running on Local Mode.
> Add Retries for OpenSearch Writer

- .github/workflows/testing.yml
- lib/sycamore/sycamore/tests/unit/test_docset.py
we would poetry install --no-root from lib/sycamore and then somehow pytest is able to import things, but ray workers could not because there is no 'sycamore' module. -> some sort of weird loop trying to reboot workers that immediately die or something
> Revert overzealous no-rootification

- lib/sycamore/sycamore/tests/unit/utils/test_similarity.py
- lib/sycamore/sycamore/utils/similarity.py
The validation logic now allows similarity_scorer to be provided without requiring similarity_query, which restores the previous behavior. We only validate that if similarity_query is provided, similarity_scorer must also be provided.
Previous version of [code](https://github.com/aryn-ai/sycamore/pull/1078/files).
Reranking initialization in [docstore](https://github.com/aryn-ai/managed-service/blob/81a5ceeb23b64e1788606fe43fd8488e7508721e/aryn/docstore/common.py#L95)
> Fix similarity assert condition for LLM Filter

- lib/sycamore/sycamore/llms/prompts/default_prompts.py
An attempt to get better json-parseable responses from the LLM with prompt tweaking. In this case we were previously getting python style dict responses.
Current, non-parseable responses with the json lib:
```
...
"someFieldWithNoValue": None
...
```
as opposed to this, which is parseable:
```
...
"someFieldWithNoValue": "None"
...
```
Another approach is to get `extract_json` to better parse these responses with regex/replace style approaches but that felt jankier and I want to avoid that as long as I can
> Prompt update for property extraction

- lib/poetry-lock/poetry-lock-all.sh
Previously, first time users who hadn't read the script could see the output abruptly stop and assume the script had completed successfully. Now, it will always either output a SUCCESS or a FAILED near the end of the output.
> Make `lib/poetry-lock/poetry-lock-all.sh` failures more obvious

- lib/sycamore/sycamore/llms/anthropic.py
- lib/sycamore/sycamore/llms/bedrock.py
- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/transforms/test_data_extraction.py
- lib/sycamore/sycamore/tests/unit/llms/test_llms.py
Adding LLM request metrics, such as wall_latency, in_token, and out_token, to the docset metadata for each LLM call.
> capturing metadata from LLMs 

- lib/sycamore/sycamore/utils/jupyter.py
Adding 3 utilities:
1. slow_pprint:  Prints large outputs slowly to prevent Jupyter from dropping output.
2. bound_memory: limit memory usage.
3. reimport: reload a module
> Add jupyter utils (Finra upstream)

- lib/sycamore/sycamore/context.py
- lib/sycamore/sycamore/tests/unit/test_context.py
Previously it would attempt to pass missing arguments as part of kwargs, but this caused issues because Ray tried to interpret them.
> Change @context_params behavior to only pass explicit arguments.

- lib/aryn-sdk/aryn_sdk/partition/partition.py
- lib/aryn-sdk/pyproject.toml
- poetry.lock
Follows [PEP 440](https://peps.python.org/pep-0440/) rules.
> Bump `aryn-sdk` version to 0.1.12.post0

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/grouped_data.py
- lib/sycamore/sycamore/tests/unit/test_docset.py
- lib/sycamore/sycamore/tests/unit/test_grouped_data.py
- lib/sycamore/sycamore/tests/unit/transforms/test_clustering.py
- lib/sycamore/sycamore/transforms/clustering.py
Implement groupby based on ray dataset groupby and show how a general
entity clustering could be used together with kmeans clustering.
> Add a groupby operator

- lib/aryn-sdk/aryn_sdk/partition/partition.py
The goal is to make `aryn-sdk` harder to use wrong: result won't "see" non-DocParse tasks and cancel won't "see" non-DocParse tasks.
> Make async DocParse methods in `aryn-sdk` not operate on non-DocParse async tasks

- lib/sycamore/sycamore/utils/extract_json.py
If None is present as a value as part of llm response, json.loads() fails.
> Fix None in llm response

- lib/sycamore/sycamore/query/schema.py
When indexing multiple datasets with different properties in finra, sycamore client was dropping properties from the dataset that was ingested later as only the first 1000 hits in the index are used to filter properties. This PR ensures random hits are selected.
> Get random hits when filtering properties in sycamore query

- lib/sycamore/sycamore/llms/anthropic.py
- lib/sycamore/sycamore/llms/gemini.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/unit/transforms/test_base_llm.py
- lib/sycamore/sycamore/transforms/base_llm.py
Implements async mode for llm_map and llm_map_elements.
Also adds asynchronous llm implementations for anthropic and gemini (+exponential backoff for openai)
I left out bedrock bc bedrock async looks like "start job, poll get job until job is complete, then download result from s3 (oh by the way tell me where in s3 to put the result" and I didn't want to deal with that. (there might be better ways  - there's a converse stream client method that can give you an async iterator over the response that might do the trick but that's a whole 'nother API to deal with)
> LLM Async mode

- lib/sycamore/sycamore/llms/anthropic.py
- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/transforms/base_llm.py
Adds batch inference modes for openai and anthropic.
I didn't do bedrock or gemini bc those involve dealing with s3 and gcs/bigquery.
OpenAI batch is pretty slow - to be able to test it I ended up using 3.5 turbo as it has far less demand and batch inferences are low priority (expires only after 24h). Anthropic haiku 3 was decently fast (competitive with async!) although that may be the same effect. I did not test it with a more modern / powerful claude.
> LLM Batch inference

- lib/aryn-sdk/aryn_sdk/partition/partition.py
- lib/sycamore/sycamore/tests/unit/transforms/test_table_extractor.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
add a model_selection param to hybrid table extractor that accepts expressions in this spec:
(take from the docstring)
```
Parse a model selection expression. Model selection expressions are of the form:
"metric cmp threshold -> model; metric cmp threshold -> model; model;"
That is, any number of conditional expression selections followed by up to one unconditional
selection expression, separated by semicolons. Expressions are processed from left to right.
- Supported metrics are "pixels" - the number of pixels in the larger dimension of the table, and
"chars" - the number of characters in the table, as detected by the partitioner's text_extractor.
- Supported comparisons are the usual set - <, >, <=, >=, ==, !=.
- The threshold must be numeric (and int or a float)
- The model must be …
```
> Add param to control how model is selected in hybrid table extractor

- lib/sycamore/sycamore/tests/unit/utils/test_extract_json.py
Discovered when checking what was not upstreamed. We've found several bugs in extract_json and failed to write a test.
> Add test for extract_json.

- lib/sycamore/sycamore/tests/integration/transforms/test_partition.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/partition.py
Currently this can be set to either PPM and PNG, and controls the format an image is encoded by the partitioner when extract_images is True. The default is PPM, which is the current behavior, but PPMs are not displayable on the console, so we provide an alternative option.
> Add extract_image_format option.

- lib/sycamore/sycamore/tests/unit/transforms/test_summarize.py
- lib/sycamore/sycamore/transforms/summarize.py
Came up when Query Database returned no docs, but summarize node still had to be executed
> Fix when no sub docs in summary document

- lib/sycamore/sycamore/tests/unit/transforms/test_table_extractor.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
With the two-stage approach it's possible that the encoder does not generate sufficient region proposals, which causes the inner topk to error out. We should fix that eventually but for now let's hack it so that if deformable fails, we fall back to tatr which (should) not have this issue
> fallback to tatr if deformable fails

- lib/sycamore/sycamore/tests/unit/transforms/test_basics.py
- lib/sycamore/sycamore/transforms/basics.py
Updated the `execute` method in `Limit` to apply the limit to `Document` instances only and not `MetadataDocument` instances.
> Fix limit transform

- lib/sycamore/sycamore/connectors/base_reader.py
- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/tests/unit/utils/test_ray_utils.py
- lib/sycamore/sycamore/transforms/base.py
- lib/sycamore/sycamore/transforms/partition.py
- lib/sycamore/sycamore/utils/ray_utils.py
A quick search on github on how 'inspect_serializability' is used shows that this is usually called when an exception of type TypeError is raised.  This way, we avoid calling this (which calls colorama.init()) prematurely.
> Inspect serialization issues only if TypeError is raised

- lib/sycamore/sycamore/connectors/aryn/ArynWriter.py
- lib/sycamore/sycamore/utils/aryn_config.py
- lib/sycamore/sycamore/writer.py
- name change: autoschema -> update_schema
- update_schema defaults to True. May need to set it to false in some of the JS scripts
- default aryn_url is now "https://api.aryn.ai/v1/storage" instead of ""
> better defaults for aryn writer

- lib/sycamore/sycamore/connectors/opensearch/opensearch_reader.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_opensearch.py
The routine for fetching all child docs for a list of parent IDs had to make multiple calls to OpenSearch to get the count of child docs for each parent.  This was done to ensure we don't do a paginated search that needs more than 10k results.  To get around the 10k result limit of the `from` pagination, I changed to the `scroll` pagination so this eliminated the need to make those calls to get doc counts.
The fetching of parent docs is now done using `mget` instead of `get`.
The doc reconstruct is also done in batches.
> Improve OpenSearch reader by batching certain operations

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/materialize.py
- lib/sycamore/sycamore/plan_nodes.py
- lib/sycamore/sycamore/query/result.py
- lib/sycamore/sycamore/tests/unit/query/test_result.py
- lib/sycamore/sycamore/tests/unit/test_materialize.py
- lib/sycamore/sycamore/tests/unit/utils/test_sycamore_logger.py
- lib/sycamore/sycamore/utils/sycamore_logger.py
1. Adds a Materialize.load_metadata() that loads all metadata documents in memory for the materialize
2. Adds a docset.get_materializes() that returns a list of all the materializes in the docset plan (param for fifo/lifo)
3. Adds a QueryResponse.get_metadata() that returns the metadata documents for the last bits of the inner sycamore pipeline
> Add metadata loading to materialize

- lib/sycamore/sycamore/tests/unit/utils/test_jupyter.py
- lib/sycamore/sycamore/utils/jupyter.py
Adds `view_pdf` function which displays the pdf as an iframe or a list of links to the files. Configurable with display_name- and url- generation functions, which can be set globally at the module level if you want. I also have a default for local files which runs a python stdlib simple http server (`file:///path/to/doc.pdf` didn't work bc jupyter sandboxes its html thingy)
> Add better view_pdf function

- lib/sycamore/sycamore/llms/__init__.py
- lib/sycamore/sycamore/query/execution/operations.py
- lib/sycamore/sycamore/query/execution/sycamore_operator.py
- lib/sycamore/sycamore/tests/integration/llms/test_anthropic.py
- lib/sycamore/sycamore/tests/integration/llms/test_bedrock.py
- lib/sycamore/sycamore/tests/integration/llms/test_gemini.py
- lib/sycamore/sycamore/tests/unit/llms/test_bedrock.py
- lib/sycamore/sycamore/utils/__init__.py
llms/__init__.py: Remove exporting the "models". Some uses expected them to be classes, and
inherited. That didn't work so switch to not exporting.
operations.py: only make one tokenizer. Making them is kinda slow.
sycamore_operator.py: importing get_knn_query is slow. Only do it on demand
utils/__init__.py: Move the requires module logic inside the fucntion so that if
someone specifies the device they want we don't end up loading torch.
> Minor fixups from testing with managed-service.

- lib/sycamore/sycamore/functions/tokenizer.py
`poetry run python -c "import import_timer; import sycamore.query.execution.operations; import_timer.show()"`
from 
```
sycamore.query.execution.operations     0.358061
```
to 
```
sycamore.query.execution.operations     0.206763
```
> load tiktoken tokenizer lazily

- lib/sycamore/sycamore/query/planner.py
- lib/sycamore/sycamore/query/planner_prompt.py
- lib/sycamore/sycamore/query/strategy.py
- lib/sycamore/sycamore/tests/integration/query/execution/test_operations.py
- lib/sycamore/sycamore/tests/unit/query/test_planner.py
- lib/sycamore/sycamore/tests/unit/query/test_strategy.py
1. Turns the planner prompt generation into a sycamore prompt object - i.e. separate prompt construction time from prompt rendering time
2. This lets us stick additional processing steps in between for intermediate mutations, e.g. rewrite question
p.s. do I need to make this work in the private planner too?
> refactor planner to add query preprocessor functionality

- lib/sycamore/sycamore/llms/anthropic.py
- lib/sycamore/sycamore/llms/bedrock.py
- lib/sycamore/sycamore/llms/gemini.py
- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/llms/test_anthropic.py
- lib/sycamore/sycamore/tests/integration/llms/test_bedrock.py
- lib/sycamore/sycamore/tests/integration/llms/test_gemini.py
- lib/sycamore/sycamore/tests/integration/llms/test_openai.py
- lib/sycamore/sycamore/tests/unit/llms/test_llms.py
- lib/sycamore/sycamore/tests/unit/transforms/test_base_llm.py
These kwargs can be passed to the constructor of the LLM object and will then be used for each generate call. Arguments passed via the generate_* methods will override the defaults.
The integ tests verify that the default arguments do in fact get applied by greatly restricting the max output tokens.
> Add support for default llm kwargs for all models.

- lib/sycamore/sycamore/llms/anthropic.py
- lib/sycamore/sycamore/llms/gemini.py
- lib/sycamore/sycamore/tests/integration/transforms/test_table_extraction.py
- lib/sycamore/sycamore/tests/unit/llms/test_llms.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
This calls an LLM to determine the cells of a table.
> Add VLMTableStructureExtractor for table structure extraction.

- apps/integration/poetry.lock
- apps/jupyter/poetry.lock
- apps/remote-processor-service/poetry.lock
- lib/poetry-lock/poetry.lock
- lib/poetry-lock/pyproject.toml
- lib/remote-processors/poetry.lock
- lib/remote-processors/pyproject.toml
- lib/sycamore/poetry.lock
- lib/sycamore/pyproject.toml
- poetry.lock
Addresses https://github.com/aryn-ai/sycamore/security/dependabot/375
> Upgrade setuptools.

- lib/sycamore/sycamore/transforms/table_structure/extract.py
previously:
```
ValueError("Invalid statement: 'default'. Did not find '->', so this is assumed to be a static statement, but the model_name was not in ('table_transformer', 'deformable_detr'))
```
Now:
```
ValueError("Bad model selection: default
Invalid statement: 'default'. Did not find '->', so this is assumed to be a static statement, but the model_name was not in ('table_transformer', 'deformable_detr'))
```
> improve model selection error message

- lib/sycamore/sycamore/tests/unit/utils/test_pdf_utils.py
- lib/sycamore/sycamore/utils/pdf_utils.py
I found this function useful in my own development. It splits a pdf Document (or each pdf in a DocSet) into multiple Documents, where each resulting Document has the specified number of pages, except possibly the last. Both the pdf binary and elements are split.
> Add a split_pdf function.

- lib/sycamore/sycamore/transforms/base_llm.py
- notebooks/default-prep-script.ipynb
- notebooks/run-notebook-tests.sh
This PR combines two commits in an attempt to the get the fast notebook tests to pass. 
Previously the _infer_prompt method would call asyncio.run to start up an
event loop in the case that an LLM was in async mode. This causes issues in
environments like Jupyter notebooks that already have a running event loop. To
avoid conflicts, we modify this to start a new thread and run the new event
loop there.
I also switched from GPT_3_5_TURBO_INSTRUCT to GPT_4O_MINI to avoid context errors.
> Fix fast notebook tests

- lib/sycamore/sycamore/llms/prompts/prompts.py
- lib/sycamore/sycamore/query/strategy.py
- lib/sycamore/sycamore/tests/unit/query/test_strategy.py
From upstreaming
- AlwaysSummarize: makes sure the plan has a summarizedata or count on the end
- OnlyRetrieval: Optimizes plan for only caring about the documents that come back
- LogPlan: Print the plan while processing; useful debug tool
- LLMRewriteQuestion: Use a llm + prompt to rewrite the question
> Add some useful planner processors

- lib/sycamore/sycamore/tests/unit/transforms/test_detr_partitioner.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
This makes additional customization possible that is otherwise difficult.
This change should have no impact on current behavior.
> Add support for a custom supplement_text function in the partitioner.

- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/grouped_data.py
- lib/sycamore/sycamore/tests/unit/test_grouped_data.py
Replace the dataset operators with docset operators to handle
materialize success handling.
> Fix materialize commit

- lib/sycamore/sycamore/llms/config.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/llms/test_openai.py
Adds o4-mini and o3. These models don't accept the temperature parameter, so we omit it for the o* series.
> Add OpenAI reasoning models.

- lib/sycamore/sycamore/connectors/opensearch/opensearch_writer.py
- lib/sycamore/sycamore/connectors/opensearch/sync.py
- lib/sycamore/sycamore/connectors/opensearch/utils.py
- lib/sycamore/sycamore/tests/manual/test_opensearch_sync.py
- lib/sycamore/sycamore/tests/unit/connectors/opensearch/test_sync.py
* Minor refactoring of opensearch_writer.py and utils.py to enable re-use.
* Manual test to run against real opensearch and experiment.
* Unit test to exercise implementation.
Next part will handle deletion/update in the source.
> First part of reliable opensearch writing -- handles new items and missing metadata on source or destination.

- lib/sycamore/sycamore/llms/gemini.py
It is still possible to pass this in as an extra parameter, but we have observed that in some cases we get better/more reliable output if we don't explicitly limit the output tokens, which was not possible with the previous approach.
> Remove default parameter for Gemini max_output_tokens.

- lib/sycamore/sycamore/llms/config.py
Drops preview label from Gemini 2.5 Flash and Gemini 2.5 Pro, and adds support for Gemini 2.5 Flash Lite Preview.
> Add support for new Gemini models.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
Refactor to ensure it uses sub functions when possible.
> Refactor Process Batch

- .gitignore
- lib/sycamore/sycamore/data/table.py
- lib/sycamore/sycamore/docset.py
- lib/sycamore/sycamore/llms/prompts/prompts.py
- lib/sycamore/sycamore/tests/integration/transforms/test_data_extraction.py
- lib/sycamore/sycamore/tests/unit/transforms/property_extraction/test_extract.py
- lib/sycamore/sycamore/tests/unit/utils/test_threading.py
- lib/sycamore/sycamore/transforms/base_llm.py
- lib/sycamore/sycamore/transforms/property_extraction/extract.py
- lib/sycamore/sycamore/transforms/property_extraction/prompts.py
- lib/sycamore/sycamore/transforms/property_extraction/strategy.py
- lib/sycamore/sycamore/transforms/summarize.py
- lib/sycamore/sycamore/utils/threading.py
- pyrightconfig.json
Minimum extract thingy
+ render_multiple_elements interface to prompts to be able to make a prompt out of a chunk of elements
+ stepthrough strategy interface to define how to step through a large document
+ schema partition strategy interface to allow me to break up a schema (e.g. if too big, if source hints are divergent)
+ some threading code to run a bunch of asyncio coroutines in another thread, block on them, and get metadata docs out
> add initial extract transform + interfaces

- lib/sycamore/sycamore/llms/prompts/default_prompts.py
- lib/sycamore/sycamore/query/client.py
- lib/sycamore/sycamore/query/planner.py
- lib/sycamore/sycamore/query/planner_prompt.py
- lib/sycamore/sycamore/query/schema.py
- lib/sycamore/sycamore/schema.py
- lib/sycamore/sycamore/tests/integration/query/test_planner.py
- lib/sycamore/sycamore/tests/integration/transforms/test_data_extraction.py
- lib/sycamore/sycamore/tests/unit/query/test_planner.py
- lib/sycamore/sycamore/tests/unit/query/test_schema.py
- lib/sycamore/sycamore/tests/unit/test_schema.py
- lib/sycamore/sycamore/tests/unit/transforms/test_schema.py
- lib/sycamore/sycamore/transforms/extract_schema.py
- lib/sycamore/sycamore/transforms/property_extraction/prompts.py
This change is a follow-up to the previous change adding SchemaV2. It migrates the existing transforms and query logic to use the new Schema model and update the tests to match.
Once this is in. We can go back and rename SchemaV2 back to Schema.
> Update Sycamore to leverage new Schema model.

- lib/sycamore/sycamore/transforms/property_extraction/types.py
otherwise I get a bunch of logs saying "Warning: NoneType is not a data type, defaulting to string"
> [extract] default to datatype.string if prediction is none

- lib/sycamore/sycamore/llms/config.py
- lib/sycamore/sycamore/llms/openai.py
- lib/sycamore/sycamore/tests/integration/llms/test_openai.py
This commit adds basic support for gpt-5, gpt-5-mini, and gpt-5-nano. More work will be required to support the verbosity and reasoning effort parameters.
> Add basic gpt-5 support.

- lib/sycamore/sycamore/schema.py
We previously tended to use "str" as the type in our schemas. This change just makes things more robust.
> Convert "str" to "string" when handling old schema format.

- lib/sycamore/sycamore/schema.py
- lib/sycamore/sycamore/tests/unit/test_schema.py
This ensures that old versions of the code can read serialized schemas, as long as they don't make use of any of the new incompatible features.
> Change Schema serialization to support backwards compatibility.

- lib/sycamore/sycamore/tests/unit/transforms/test_table_transfomers.py
- lib/sycamore/sycamore/transforms/table_structure/table_transformers.py
Previous Errors
- Dropped tokens were incorrectly assigned to wrong columns
- Mismatched row/column dimensions when inserting new rows/columns, row bboxs were not updated when inserting columns and vice versa
- Invalid bounding boxes [0, 0, 0, 0] caused by mismatched row/column dimensions
Changes Made
- Refactored logic into separate helper functions
- Fixed row/column intersection logic to properly handle tokens outside existing table boundaries
- Fixed row/column dimension mismatch by extending rows/columns to cover new dimensions
- Re-enabled and updated test for the function
> Rewrite union_dropped_token_with_cells and update tests.

- lib/sycamore/sycamore/connectors/file/file_scan.py
- lib/sycamore/sycamore/tests/unit/scans/test_file_scan.py
When you specify a binary_format to BinaryScan, it restricts the files to only those of the specified format. Previously there was an inconsistency in behavior between Ray and local modes. In Ray mode, the extensions were specified in a case-insensitive way, whereas in local mode they were case sensitive.
This commit makes both case insensitive.
> Make file extension comparison case insensitive in local mode.

- lib/sycamore/sycamore/transforms/detr_partitioner.py
- lib/sycamore/sycamore/transforms/similarity.py
- lib/sycamore/sycamore/transforms/table_structure/extract.py
These dropped the naive case for DETR partitioning from ~18 seconds to ~14.
Using torch.autocast() with the DETR table model caused wrong answers; so, we don't use it there.
> Torch speedups from benchmarking: low hanging fruit.

- lib/sycamore/sycamore/llms/llms.py
- lib/sycamore/sycamore/transforms/base_llm.py
- lib/sycamore/sycamore/transforms/detr_partitioner.py
We found a file which currently causes persistent errors and want to use fallback parameters which work don't get persistent errors but may have lower quality.
The llm hack lets us see the exact prompts and replies we are sending/getting from an LLM.
> Add a hack so we can disable the automatic detr retry.  Add a hack to help debug LLM prompts and results.

- lib/sycamore/sycamore/schema.py
- lib/sycamore/sycamore/tests/unit/test_schema.py
Sets don't get handled correctly by libraries like httpx, so we convert to lists during serialization. Pydantic will automatically convert from list back to set during validation.
> Serialize set value attributes as a list.
